import type { DiagramSpec } from './diagrams';

export type ApiPerformanceKey = 'pagination' | 'async-logging' | 'caching' | 'compression' | 'connection-pool' | 'multiplexing' | 'async-processing' | 'rate-limit';
const http = { label: 'RFC 9110 — HTTP Semantics', url: 'https://www.rfc-editor.org/rfc/rfc9110' };

const diagrams: Record<ApiPerformanceKey, DiagramSpec> = {
  pagination:{title:'Paginação: limite trabalho por request',description:'Cursor/keyset pagination evita retornar datasets enormes. O servidor entrega uma página limitada e um cursor para continuar.',width:980,height:390,nodes:[{id:'c',label:'1. GET /orders?limit=50',x:30,y:150,kind:'client'},{id:'a',label:'2. API\nvalida limit/cursor',x:300,y:150,kind:'control'},{id:'db',label:'3. DB index\nWHERE id > cursor',x:560,y:150,kind:'data'},{id:'r',label:'4. 50 items\nnextCursor',x:800,y:150,kind:'network'}],edges:[{from:'c',to:'a',label:'1 request'},{from:'a',to:'db',label:'2 bounded query'},{from:'db',to:'r',label:'3 page'},{from:'r',to:'c',label:'4 response'}],sources:[http]},
  'async-logging':{title:'Async logging: logging fora do critical path',description:'A resposta não deve esperar escrita remota de log. A aplicação escreve num buffer/agent e o pipeline envia depois.',width:980,height:390,nodes:[{id:'req',label:'1. Request',x:35,y:110,kind:'client'},{id:'api',label:'2. API',x:275,y:110,kind:'workload'},{id:'resp',label:'3. Response rápido',x:545,y:55,kind:'network'},{id:'buf',label:'4. Log buffer / agent',x:545,y:205,kind:'control'},{id:'store',label:'5. Log pipeline / store',x:805,y:205,kind:'data'}],edges:[{from:'req',to:'api',label:'1 request'},{from:'api',to:'resp',label:'2 respond'},{from:'api',to:'buf',label:'3 enqueue log'},{from:'buf',to:'store',label:'4 async batch'}],sources:[http]},
  caching:{title:'API caching: responder sem repetir trabalho caro',description:'Caches podem existir no cliente, CDN/reverse proxy ou aplicação. Chave, TTL e invalidação fazem parte do desenho.',width:980,height:390,nodes:[{id:'c',label:'1. Client',x:35,y:150,kind:'client'},{id:'cache',label:'2. Cache\nkey + TTL',x:300,y:150,kind:'data'},{id:'api',label:'3. API',x:560,y:150,kind:'workload'},{id:'db',label:'4. Database',x:800,y:150,kind:'data'},{id:'hit',label:'HIT: resposta imediata',x:300,y:305,kind:'network'}],edges:[{from:'c',to:'cache',label:'1 lookup'},{from:'cache',to:'hit',label:'2a hit'},{from:'cache',to:'api',label:'2b miss'},{from:'api',to:'db',label:'3 query'},{from:'db',to:'cache',label:'4 populate'},{from:'hit',to:'c',label:'5 response'}],sources:[http]},
  compression:{title:'Payload compression: menos bytes, mais CPU',description:'O cliente anuncia algoritmos aceitos; o servidor comprime respostas quando o ganho compensa CPU e latência.',width:980,height:390,nodes:[{id:'c',label:'1. Client\nAccept-Encoding: br,gzip',x:35,y:150,kind:'client'},{id:'api',label:'2. API',x:315,y:150,kind:'workload'},{id:'cmp',label:'3. Compressor\nBrotli / gzip',x:570,y:150,kind:'control'},{id:'wire',label:'4. Menos bytes\nContent-Encoding',x:815,y:150,kind:'network'}],edges:[{from:'c',to:'api',label:'1 negotiate'},{from:'api',to:'cmp',label:'2 payload'},{from:'cmp',to:'wire',label:'3 compress'},{from:'wire',to:'c',label:'4 transfer'}],sources:[http]},
  'connection-pool':{title:'Connection pool: reutilizar conexões caras',description:'A API mantém um número limitado de conexões abertas para database/upstreams. Requests emprestam e devolvem conexões.',width:980,height:390,nodes:[{id:'r',label:'1. Requests concorrentes',x:25,y:150,kind:'client'},{id:'api',label:'2. API workers',x:265,y:150,kind:'workload'},{id:'pool',label:'3. Connection Pool\nmin/max + timeout',x:530,y:150,kind:'control'},{id:'db',label:'4. Database',x:805,y:150,kind:'data'}],edges:[{from:'r',to:'api',label:'1 arrive'},{from:'api',to:'pool',label:'2 borrow'},{from:'pool',to:'db',label:'3 reuse connection'},{from:'db',to:'pool',label:'4 release',bidirectional:true}],sources:[http]},
  multiplexing:{title:'HTTP/2 multiplexing e keep-alive',description:'Uma conexão pode transportar múltiplos streams concorrentes, reduzindo custo de conexões e serialização no cliente.',width:980,height:390,nodes:[{id:'c',label:'1. Client',x:35,y:160,kind:'client'},{id:'conn',label:'2. 1 conexão HTTP/2',x:315,y:160,kind:'network'},{id:'s1',label:'3. Stream 1',x:610,y:55,kind:'workload'},{id:'s2',label:'3. Stream 2',x:610,y:155,kind:'workload'},{id:'s3',label:'3. Stream 3',x:610,y:255,kind:'workload'}],edges:[{from:'c',to:'conn',label:'1 persistent connection'},{from:'conn',to:'s1',label:'2 multiplex'},{from:'conn',to:'s2',label:'2 multiplex'},{from:'conn',to:'s3',label:'2 multiplex'}],sources:[http]},
  'async-processing':{title:'Async processing: responder 202 e processar depois',description:'Para trabalhos longos, a API valida e enfileira o job, retorna 202 + job ID e um worker processa fora do request path.',width:980,height:390,nodes:[{id:'c',label:'1. Client',x:35,y:120,kind:'client'},{id:'api',label:'2. API\nvalidate + enqueue',x:275,y:120,kind:'control'},{id:'q',label:'3. Queue',x:535,y:120,kind:'data'},{id:'w',label:'4. Worker',x:790,y:120,kind:'workload'},{id:'ack',label:'202 Accepted\njobId + status URL',x:275,y:285,kind:'network'}],edges:[{from:'c',to:'api',label:'1 POST'},{from:'api',to:'q',label:'2 enqueue'},{from:'api',to:'ack',label:'3 immediate response'},{from:'q',to:'w',label:'4 process'},{from:'ack',to:'c',label:'5 status'}],sources:[http]},
  'rate-limit':{title:'Rate limiting e backpressure',description:'Limites protegem capacidade compartilhada. O gateway mede identidade/tenant, aplica quota e devolve 429 quando necessário.',width:980,height:390,nodes:[{id:'c',label:'1. Clients',x:35,y:150,kind:'client'},{id:'rl',label:'2. Rate Limiter\nquota / token bucket',x:300,y:150,kind:'security'},{id:'api',label:'3. API capacity',x:590,y:150,kind:'workload'},{id:'429',label:'4. 429 + Retry-After',x:300,y:305,kind:'network'}],edges:[{from:'c',to:'rl',label:'1 request'},{from:'rl',to:'api',label:'2 allowed'},{from:'rl',to:'429',label:'3 over limit'},{from:'429',to:'c',label:'4 back off'}],sources:[http]},
};

export function getApiPerformanceDiagram(key: ApiPerformanceKey): DiagramSpec { return diagrams[key]; }
