import type { DiagramSpec } from './diagrams';

export type ApiSecurityKey = 'tls' | 'identity' | 'gateway' | 'validation' | 'mtls';
const http = { label: 'RFC 9110 — HTTP Semantics', url: 'https://www.rfc-editor.org/rfc/rfc9110' };
const owasp = { label: 'OWASP API Security Top 10', url: 'https://owasp.org/API-Security/' };

const diagrams: Record<ApiSecurityKey, DiagramSpec> = {
  tls:{title:'API security: TLS protege o canal',description:'TLS autentica o endpoint e cifra dados em trânsito. A API ainda precisa de autenticação e autorização no nível da aplicação.',width:980,height:390,nodes:[{id:'c',label:'1. API Client',x:40,y:150,kind:'client'},{id:'tls',label:'2. TLS handshake\ncert + hostname',x:310,y:150,kind:'security'},{id:'api',label:'3. HTTPS API',x:610,y:150,kind:'workload'},{id:'data',label:'4. Encrypted request/response',x:310,y:305,kind:'network'}],edges:[{from:'c',to:'tls',label:'1 connect'},{from:'tls',to:'api',label:'2 verify'},{from:'c',to:'data',label:'3 encrypted traffic',bidirectional:true},{from:'data',to:'api',label:'4 protected channel',bidirectional:true}],sources:[http,owasp]},
  identity:{title:'Autenticação e autorização: identidade antes do recurso',description:'O IdP emite um token curto; gateway/API valida assinatura, issuer, audience, expiração e scopes/claims antes de autorizar.',width:980,height:390,nodes:[{id:'c',label:'1. Client',x:35,y:150,kind:'client'},{id:'idp',label:'2. IdP / OAuth/OIDC',x:275,y:60,kind:'security'},{id:'tok',label:'3. Access Token',x:275,y:235,kind:'data'},{id:'api',label:'4. API\nvalidate + authorize',x:585,y:150,kind:'security'},{id:'res',label:'5. Protected Resource',x:825,y:150,kind:'workload'}],edges:[{from:'c',to:'idp',label:'1 authenticate'},{from:'idp',to:'tok',label:'2 issue token'},{from:'tok',to:'c',label:'3 credential'},{from:'c',to:'api',label:'4 Bearer token'},{from:'api',to:'res',label:'5 authorize'}],sources:[owasp]},
  gateway:{title:'API Gateway: policy enforcement centralizado',description:'O gateway pode terminar TLS, autenticar, aplicar rate limit, roteamento e observabilidade. Regras de negócio e autorização fina continuam no serviço.',width:980,height:390,nodes:[{id:'c',label:'1. Clients',x:35,y:150,kind:'client'},{id:'waf',label:'2. WAF / DDoS',x:255,y:150,kind:'security'},{id:'gw',label:'3. API Gateway\nauth + rate limit + routing',x:495,y:150,kind:'control'},{id:'a',label:'4. Service A',x:795,y:75,kind:'workload'},{id:'b',label:'4. Service B',x:795,y:235,kind:'workload'}],edges:[{from:'c',to:'waf',label:'1 HTTPS'},{from:'waf',to:'gw',label:'2 filtered'},{from:'gw',to:'a',label:'3 route'},{from:'gw',to:'b',label:'3 route'}],sources:[owasp]},
  validation:{title:'Input validation: não confiar no payload',description:'Valide schema, tipos, tamanho, ranges e formato antes da lógica de negócio. Queries devem usar parâmetros e limites explícitos.',width:980,height:390,nodes:[{id:'c',label:'1. Untrusted input',x:35,y:150,kind:'client'},{id:'schema',label:'2. Schema + size limits',x:300,y:150,kind:'security'},{id:'auth',label:'3. Authorization\nobject/function level',x:565,y:150,kind:'security'},{id:'svc',label:'4. Business logic',x:815,y:150,kind:'workload'},{id:'rej',label:'400 / 403 rejected',x:300,y:305,kind:'network'}],edges:[{from:'c',to:'schema',label:'1 parse'},{from:'schema',to:'auth',label:'2 valid input'},{from:'auth',to:'svc',label:'3 allowed'},{from:'schema',to:'rej',label:'invalid'},{from:'auth',to:'rej',label:'forbidden'}],sources:[owasp]},
  mtls:{title:'mTLS para service-to-service',description:'Ambos os workloads apresentam certificados. A workload identity liga certificado a serviço e permite autenticação mútua antes da chamada.',width:980,height:390,nodes:[{id:'ca',label:'1. Workload CA / Identity',x:335,y:50,kind:'security'},{id:'a',label:'2. Service A\nclient cert',x:60,y:210,kind:'workload'},{id:'tls',label:'3. mTLS handshake\nboth verify certs',x:350,y:210,kind:'security'},{id:'b',label:'4. Service B\nserver cert',x:690,y:210,kind:'workload'}],edges:[{from:'ca',to:'a',label:'1 issue identity'},{from:'ca',to:'b',label:'1 issue identity'},{from:'a',to:'tls',label:'2 present cert'},{from:'b',to:'tls',label:'3 present cert'},{from:'tls',to:'b',label:'4 encrypted authorized channel',bidirectional:true}],sources:[owasp]},
};

export function getApiSecurityDiagram(key: ApiSecurityKey): DiagramSpec { return diagrams[key]; }
