export const diagramTextEn: Record<string, string> = {
  // Kubernetes
  'Arquitetura básica do Kubernetes': 'Basic Kubernetes architecture',
  'O API Server é o ponto central do control plane. Scheduler e controllers observam o estado pela API; o etcd persiste o estado; kubelets executam Pods nos nodes.': 'The API Server is the central entry point of the control plane. The scheduler and controllers observe state through the API, etcd persists cluster state, and kubelets run Pods on nodes.',
  'Caminho de tráfego e readiness': 'Traffic path and readiness',
  'Ingress encaminha HTTP/HTTPS para um Service. O Service representa endpoints de Pods; quando readiness falha, o endpoint correspondente deixa de ser considerado pronto para tráfego.': 'Ingress forwards HTTP/HTTPS traffic to a Service. The Service represents Pod endpoints; when readiness fails, the corresponding endpoint is no longer considered ready for traffic.',
  'Control plane altamente disponível com etcd em quorum': 'Highly available control plane with etcd quorum',
  'Uma topologia HA distribui API Servers atrás de um load balancer e mantém múltiplos membros etcd. Em um cluster etcd de três membros, são necessários dois membros para manter quorum.': 'An HA topology distributes API Servers behind a load balancer and maintains multiple etcd members. In a three-member etcd cluster, two members are required to maintain quorum.',
  'Pipeline de segurança de uma requisição à API': 'API request security pipeline',
  'Uma requisição ao API Server passa por autenticação, autorização e admission control antes de o objeto aceito ser persistido. Cada etapa responde a uma pergunta de segurança diferente.': 'A request to the API Server passes through authentication, authorization, and admission control before the accepted object is persisted. Each stage answers a different security question.',
  'Escolha do controlador de workload': 'Choosing a workload controller',
  'A escolha depende principalmente de identidade, estado e necessidade de executar uma instância por node.': 'The choice mainly depends on identity, state, and whether one instance must run per node.',
  'Falha de readiness sem reinício automático': 'Readiness failure without automatic restart',
  'O efeito principal é retirar o Pod do caminho normal de tráfego, não reiniciar o processo.': 'The main effect is removing the Pod from the normal traffic path, not restarting the process.',
  'Troubleshooting de Service sem endpoints': 'Troubleshooting a Service with no endpoints',
  'A investigação começa na relação selector → labels → readiness → EndpointSlice, antes de culpar a camada de rede.': 'Investigation starts with selector → labels → readiness → EndpointSlice before blaming the network layer.',
  'Quorum do etcd com três membros': 'etcd quorum with three members',
  'Três membros toleram a falha de um membro; dois membros restantes ainda formam a maioria necessária.': 'Three members tolerate one member failure; the two remaining members still form the required majority.',

  // Docker
  'Imagem, container, filesystem e volume': 'Image, container, filesystem, and volume',
  'A imagem fornece camadas somente leitura. Ao iniciar um container, o runtime adiciona uma camada gravável efêmera; volumes persistem dados fora dessa camada.': 'The image provides read-only layers. When a container starts, the runtime adds an ephemeral writable layer; volumes persist data outside that layer.',
  'Multi-stage build: builder separado da imagem final': 'Multi-stage build: builder separated from the final image',
  'A fase de build contém compiladores e dependências de desenvolvimento. COPY --from transfere somente o artefato necessário para a imagem final, reduzindo tamanho e superfície de ataque.': 'The build stage contains compilers and development dependencies. COPY --from transfers only the required artifact to the final image, reducing size and attack surface.',
  'Isolamento de container no Linux': 'Linux container isolation',
  'Containers não possuem um kernel próprio. O processo executa sobre o kernel do host; namespaces isolam visões de recursos, cgroups controlam recursos e mecanismos como capabilities/seccomp reduzem privilégios.': 'Containers do not have their own kernel. The process runs on the host kernel; namespaces isolate resource views, cgroups control resources, and mechanisms such as capabilities and seccomp reduce privileges.',
  'Supply chain de uma imagem de produção': 'Production image supply chain',
  'Um pipeline maduro associa código, build, imagem imutável, metadados de provenance/SBOM e política de implantação. O digest identifica o conteúdo da imagem independentemente de uma tag mutável.': 'A mature pipeline links source code, build, immutable image, provenance/SBOM metadata, and deployment policy. The digest identifies image content independently of a mutable tag.',
  'Uma imagem pode originar vários containers': 'One image can create multiple containers',
  'A imagem é reutilizável; cada container possui identidade de runtime e camada gravável independente.': 'The image is reusable; each container has its own runtime identity and independent writable layer.',
  'Fluxo de um multi-stage build': 'Multi-stage build flow',
  'O artefato atravessa a fronteira entre stages; o toolchain de build não atravessa.': 'The artifact crosses the stage boundary; the build toolchain does not.',
  'Container versus máquina virtual': 'Container versus virtual machine',
  'A principal diferença arquitetural é o kernel: containers compartilham o kernel do host; VMs possuem kernel guest próprio.': 'The main architectural difference is the kernel: containers share the host kernel, while VMs have their own guest kernel.',

  // Linux
  'Processo Linux, descritores e interfaces virtuais do kernel': 'Linux processes, descriptors, and virtual kernel interfaces',
  'Um processo possui PID e tabela de descritores. Descritores podem referenciar arquivos, pipes ou sockets. /proc expõe informações do processo e do kernel como uma interface virtual.': 'A process has a PID and descriptor table. Descriptors can reference files, pipes, or sockets. /proc exposes process and kernel information through a virtual interface.',
  'Filesystem cheio: blocos e inodes são recursos diferentes': 'Full filesystem: blocks and inodes are different resources',
  'Um filesystem pode ficar incapaz de criar novos arquivos mesmo com bytes livres se todos os inodes estiverem alocados. df -h observa capacidade em blocos; df -i observa disponibilidade de inodes.': 'A filesystem may be unable to create new files even with free bytes when all inodes are allocated. df -h shows block capacity; df -i shows inode availability.',
  'Da aplicação ao socket e à pilha de rede do kernel': 'From the application to the socket and kernel network stack',
  'Aplicações usam sockets por meio de syscalls. ss consulta informações de sockets no kernel; ip inspeciona endereços, links e rotas que influenciam o caminho do pacote.': 'Applications use sockets through system calls. ss inspects socket information in the kernel; ip inspects addresses, links, and routes that influence the packet path.',
  'Espaço em bytes livre, mas nenhum inode disponível': 'Free byte capacity but no inodes available',
  'Capacidade de dados e capacidade de criar novos objetos são dimensões distintas.': 'Data capacity and the ability to create new objects are separate dimensions.',
  'Processo com múltiplas threads': 'Process with multiple threads',
  'Threads compartilham recursos do processo, mas cada uma possui fluxo de execução próprio.': 'Threads share process resources, but each has its own execution flow.',
  'Load alto não implica CPU saturada': 'High load does not necessarily mean saturated CPU',
  'A investigação separa tarefas que querem CPU de tarefas que estão bloqueadas esperando recursos.': 'The investigation separates tasks waiting for CPU from tasks blocked while waiting for resources.',

  // Networking
  'Comunicação local e roteada entre hosts': 'Local and routed communication between hosts',
  'Dentro da mesma subnet, hosts resolvem o próximo salto local e trocam frames. Para outra subnet, o host envia o pacote ao default gateway; routers encaminham com base na tabela de rotas até a rede de destino.': 'Within the same subnet, hosts resolve the local next hop and exchange frames. For another subnet, the host sends the packet to the default gateway; routers forward it according to routing tables until it reaches the destination network.',
  'Do nome DNS à sessão de aplicação': 'From a DNS name to an application session',
  'Uma aplicação pode resolver um nome via DNS, abrir uma sessão TCP quando o protocolo exige transporte confiável e então trocar dados de aplicação. UDP remove o estabelecimento de conexão e entrega datagramas sem as garantias de TCP.': 'An application can resolve a name through DNS, open a TCP session when the protocol requires reliable transport, and then exchange application data. UDP removes connection establishment and delivers datagrams without TCP guarantees.',
  'Duas redes comunicando-se por roteamento ou VPN site-to-site': 'Two networks communicating through routing or a site-to-site VPN',
  'Para duas redes distintas se comunicarem, cada lado precisa conhecer a rota para a rede remota e os dispositivos de segurança devem permitir o tráfego. Quando há Internet entre os sites, um túnel VPN pode transportar os pacotes privados de forma protegida.': 'For two different networks to communicate, each side must know the route to the remote network and security devices must allow the traffic. When the Internet lies between the sites, a VPN tunnel can securely transport private packets.',
  'Troubleshooting por camadas: rota, política, transporte e aplicação': 'Layered troubleshooting: routing, policy, transport, and application',
  'Uma investigação eficiente verifica primeiro endereçamento e rota, depois políticas de firewall/NAT, estados de transporte e finalmente o protocolo de aplicação. Ferramentas como ping, traceroute, ip route, ss, tcpdump e dig ajudam a separar as camadas.': 'An efficient investigation checks addressing and routing first, then firewall/NAT policies, transport states, and finally the application protocol. Tools such as ping, traceroute, ip route, ss, tcpdump, and dig help isolate the layers.',
  'VPN site-to-site com roteamento bidirecional': 'Site-to-site VPN with bidirectional routing',
  'O túnel sozinho não cria conectividade completa: rotas e políticas precisam existir nos dois sentidos.': 'The tunnel alone does not provide complete connectivity: routes and policies must exist in both directions.',
  'Checklist de comunicação entre duas redes': 'Two-network communication checklist',
  'Conectividade exige caminho de ida, caminho de retorno e política permissiva; apenas criar um link entre redes não é suficiente.': 'Connectivity requires a forward path, return path, and permitting policy; simply creating a link between networks is not enough.',
  'Porta pertence ao transporte; nem todo protocolo usa porta': 'Ports belong to transport protocols; not every protocol uses a port',
  'Serviços de aplicação normalmente usam TCP ou UDP. Protocolos como ICMP e ESP ficam diretamente sobre IP e portanto não possuem porta TCP/UDP.': 'Application services normally use TCP or UDP. Protocols such as ICMP and ESP run directly over IP and therefore do not use TCP/UDP ports.',

  // Security
  'Identidade, autorização e proteção de dados': 'Identity, authorization, and data protection',
  'Segurança combina controles complementares: autenticação estabelece quem é a identidade, autorização limita o que ela pode fazer e criptografia protege dados em trânsito ou repouso.': 'Security combines complementary controls: authentication establishes identity, authorization limits what that identity can do, and encryption protects data in transit or at rest.',
  'TLS 1.3: autenticação do servidor e estabelecimento de chaves': 'TLS 1.3: server authentication and key establishment',
  'No handshake TLS 1.3, cliente e servidor negociam parâmetros criptográficos e derivam chaves de tráfego. O servidor normalmente apresenta um certificado para provar sua identidade antes do canal de aplicação protegido.': 'During the TLS 1.3 handshake, client and server negotiate cryptographic parameters and derive traffic keys. The server normally presents a certificate to prove its identity before the protected application channel is established.',
  'Arquitetura em camadas: edge, identidade, aplicação e secrets': 'Layered architecture: edge, identity, application, and secrets',
  'Uma arquitetura segura combina segmentação e controles em diferentes pontos. WAF/firewall reduzem exposição no edge, identidade limita acesso, workloads ficam segmentados e segredos são obtidos de um sistema dedicado em vez de embutidos em código.': 'A secure architecture combines segmentation and controls at different points. WAF/firewall reduce edge exposure, identity limits access, workloads remain segmented, and secrets are obtained from a dedicated system instead of being embedded in code.',
  'Zero Trust: decisão de acesso baseada em identidade e contexto': 'Zero Trust: access decisions based on identity and context',
  'Zero Trust não considera a localização de rede como prova suficiente de confiança. Cada acesso é avaliado usando identidade, política e contexto, com privilégio mínimo e monitorização contínua.': 'Zero Trust does not treat network location as sufficient proof of trust. Each access request is evaluated using identity, policy, and context, with least privilege and continuous monitoring.',
  'OAuth 2.0 autoriza; OpenID Connect adiciona identidade': 'OAuth 2.0 authorizes; OpenID Connect adds identity',
  'O access token é usado para acessar recursos protegidos. Em OIDC, o ID Token carrega afirmações sobre a autenticação e identidade do utilizador.': 'The access token is used to access protected resources. In OIDC, the ID Token carries claims about user authentication and identity.',
  'Cadeia de confiança PKI': 'PKI chain of trust',
  'A confiança flui do trust store local para a raiz, desta para uma CA intermediária e então para o certificado do servidor, desde que todas as verificações sejam válidas.': 'Trust flows from the local trust store to the root, from the root to an intermediate CA, and then to the server certificate, provided every validation succeeds.',
  'Acesso Zero Trust por recurso': 'Zero Trust access per resource',
  'A política decide cada acesso com base em identidade e contexto, em vez de liberar toda a rede após uma conexão inicial.': 'Policy evaluates each access request based on identity and context instead of opening the entire network after an initial connection.',

  // Helm
  'Chart → templates → manifests → release': 'Chart → templates → manifests → release',
  'Um chart combina metadados, values e templates. O Helm renderiza manifests Kubernetes e registra a instalação como uma release.': 'A chart combines metadata, values, and templates. Helm renders Kubernetes manifests and records the installation as a release.',
  'Renderização e validação de templates': 'Template rendering and validation',
  'Templates recebem values, funções e pipelines. A validação deve acontecer antes do deploy com lint e renderização local.': 'Templates receive values, functions, and pipelines. Validation should happen before deployment through linting and local rendering.',
  'Chart pai, subcharts e configuração por ambiente': 'Parent chart, subcharts, and environment configuration',
  'Dependências devem ter contratos claros. O chart pai coordena subcharts; ambientes devem sobrescrever apenas diferenças necessárias.': 'Dependencies should have clear contracts. The parent chart coordinates subcharts; environments should override only the necessary differences.',
  'Helm sob GitOps': 'Helm under GitOps',
  'Git mantém o estado desejado; Argo CD renderiza ou consome Helm e reconcilia o cluster. Rollback preferencialmente acontece revertendo Git.': 'Git stores desired state; Argo CD renders or consumes Helm and reconciles the cluster. Rollback should preferably happen by reverting Git.',
  'Chart reutilizável, releases concretas': 'Reusable chart, concrete releases',
  'Um mesmo chart pode originar múltiplas releases com configurações diferentes.': 'The same chart can create multiple releases with different configurations.',
  'Pipeline de validação de chart': 'Chart validation pipeline',
  'Valide estrutura, renderização e políticas antes do deploy.': 'Validate structure, rendering, and policies before deployment.',
  'Helm renderizado pelo Argo CD': 'Helm rendered by Argo CD',
  'Argo CD usa Git como fonte de verdade e o Helm como motor de renderização.': 'Argo CD uses Git as the source of truth and Helm as the rendering engine.',

  // Terraform
  'Configuração declarativa → grafo → plano → apply': 'Declarative configuration → graph → plan → apply',
  'Terraform descreve estado desejado, constrói um grafo de dependências, compara configuração/estado/realidade e executa as mudanças planejadas.': 'Terraform describes desired state, builds a dependency graph, compares configuration/state/real infrastructure, and executes the planned changes.',
  'Root module, child modules e state remoto': 'Root module, child modules, and remote state',
  'Módulos encapsulam recursos e expõem variables/outputs. O state remoto é compartilhado com proteção, locking quando suportado e controle de acesso.': 'Modules encapsulate resources and expose variables/outputs. Remote state is shared with protection, locking when supported, and access control.',
  'Refatoração segura e reconciliação de identidade': 'Safe refactoring and identity reconciliation',
  'Import, moved blocks e operações de state tratam identidade de recursos. O objetivo é alinhar configuração, state e infraestrutura sem recriação indevida.': 'Import, moved blocks, and state operations manage resource identity. The goal is to align configuration, state, and infrastructure without unnecessary recreation.',
  'Pipeline de governança e drift': 'Governance and drift pipeline',
  'CI valida e gera plan; revisão/policy decide promoção; apply usa o artefato aprovado. Detecção de drift compara estado desejado e realidade antes de qualquer correção.': 'CI validates and generates a plan; review/policy decides promotion; apply uses the approved artifact. Drift detection compares desired state with real infrastructure before any correction.',
  'State liga HCL a objetos reais': 'State links HCL to real objects',
  'O state mantém identidade e metadados entre configuração declarativa e infraestrutura remota.': 'State preserves identity and metadata between declarative configuration and remote infrastructure.',
  'Lock serializa writers do state': 'Lock serializes state writers',
  'Dois applies concorrentes não devem alterar o mesmo state simultaneamente.': 'Two concurrent applies must not modify the same state at the same time.',
  'Resource, data source e module': 'Resource, data source, and module',
  'Resource gerencia; data source consulta; module encapsula composição.': 'A resource manages; a data source reads; a module encapsulates composition.',
  'Camadas de abstração do Terraform': 'Terraform abstraction layers',
  'Modules usam resources/data sources; estes são implementados por providers que conversam com APIs.': 'Modules use resources/data sources; providers implement them and communicate with external APIs.',
  'Workspace: mesma configuração, state separado': 'Workspace: same configuration, separate state',
  'O código é compartilhado, mas cada workspace mantém sua própria instância de state.': 'The code is shared, but each workspace maintains its own state instance.',
  'Recuperação de state: preservar → diagnosticar → reconciliar': 'State recovery: preserve → diagnose → reconcile',
  'A recuperação segura começa por backup e observação antes de qualquer mutação do state.': 'Safe recovery starts with backup and observation before any state mutation.',
  'Decisão de correção de drift': 'Drift correction decision',
  'Drift não deve ser corrigido automaticamente sem decidir qual estado é a fonte correta.': 'Drift should not be corrected automatically before deciding which state represents the intended source of truth.',

  // Ansible
  'Control node → inventory → playbook → managed nodes': 'Control node → inventory → playbook → managed nodes',
  'Ansible é normalmente agentless: o control node seleciona hosts pelo inventory e executa módulos definidos por tasks no playbook.': 'Ansible is normally agentless: the control node selects hosts from inventory and runs modules defined by tasks in the playbook.',
  'Roles, handlers e precedence de variáveis': 'Roles, handlers, and variable precedence',
  'Roles organizam reutilização. Variáveis entram por múltiplas fontes e seguem regras de precedência; handlers executam ações notificadas apenas quando há mudança.': 'Roles organize reuse. Variables come from multiple sources and follow precedence rules; handlers run notified actions only when a change occurs.',
  'Automação em escala com inventories dinâmicos e execution environments': 'Automation at scale with dynamic inventories and execution environments',
  'Em escala, inventário vem de APIs/CMDBs, execution environments fixam dependências e a execução precisa ser observável, testável e controlada por lotes.': 'At scale, inventory comes from APIs/CMDBs, execution environments pin dependencies, and execution must be observable, testable, and controlled in batches.',
  'Idempotência: convergir, depois no-op': 'Idempotency: converge, then no-op',
  'A primeira execução pode mudar o host; execuções seguintes devem permanecer sem mudança quando o estado desejado já existe.': 'The first run may change the host; subsequent runs should remain unchanged when the desired state already exists.',
  'Task, handler e role': 'Task, handler, and role',
  'A role contém componentes; tasks podem notificar handlers quando alteram o host.': 'A role contains components; tasks can notify handlers when they change the host.',
  'Terraform provisiona; Ansible configura': 'Terraform provisions; Ansible configures',
  'A fronteira não é absoluta, mas separar lifecycle de infraestrutura da configuração reduz acoplamento.': 'The boundary is not absolute, but separating infrastructure lifecycle from system configuration reduces coupling.',
  'Diagnóstico de changed=true permanente': 'Diagnosing persistent changed=true',
  'Compare entrada determinística, estado real e regra changed antes de culpar o módulo.': 'Compare deterministic input, actual state, and the changed rule before blaming the module.',
  'Contrato previsível de uma role': 'Predictable role contract',
  'Defaults e inputs entram na role; tasks mudam estado; handlers reagem a mudanças reais.': 'Defaults and inputs enter the role; tasks change state; handlers react to actual changes.',
  'Rollout em batches': 'Batch rollout',
  'O controlador aplica mudanças em pequenos grupos e só avança após validação.': 'The controller applies changes to small groups and advances only after validation.',
  'Troubleshooting por diferenças entre hosts': 'Troubleshooting differences between hosts',
  'O objetivo é encontrar a primeira divergência entre contexto, variáveis, dependências e privilégios.': 'The goal is to find the first divergence in context, variables, dependencies, or privileges.',

  // CI/CD and GitOps
  'Continuous Integration: feedback rápido por commit': 'Continuous Integration: fast feedback per commit',
  'Cada mudança passa por checkout, build, lint, testes e geração de artefato. Falhas devem aparecer cedo e bloquear promoção.': 'Every change goes through checkout, build, lint, tests, and artifact generation. Failures should surface early and block promotion.',
  'Promotion: o mesmo artefato atravessa ambientes': 'Promotion: the same artifact moves across environments',
  'O artefato deve ser construído uma vez e promovido por ambientes com configuração externa, gates e rollback.': 'The artifact should be built once and promoted across environments with external configuration, gates, and rollback.',
  'GitOps: reconciliação contínua de estado desejado': 'GitOps: continuous reconciliation of desired state',
  'CI publica o artefato e atualiza a referência declarativa no Git. Argo CD compara desired vs live e sincroniza conforme a política configurada.': 'CI publishes the artifact and updates the declarative reference in Git. Argo CD compares desired vs live state and synchronizes according to the configured policy.',
  'Supply chain, OIDC e orquestração de sync': 'Supply chain, OIDC, and sync orchestration',
  'Pipelines especialistas reduzem credenciais persistentes com OIDC, usam provenance/SBOM/policies e controlam ordem de implantação com phases/waves quando necessário.': 'Expert pipelines reduce persistent credentials with OIDC, use provenance/SBOM/policies, and control deployment order with phases/waves when required.',
  'Delivery versus Deployment': 'Delivery versus Deployment',
  'A diferença principal está no gate final para produção.': 'The main difference is the final production gate.',
  'Desired vs live → OutOfSync → reconcile': 'Desired vs live → OutOfSync → reconcile',
  'Drift é uma diferença entre Git e o cluster; self-heal reaplica desired state e prune remove recursos órfãos do desired state.': 'Drift is a difference between Git and the cluster; self-heal reapplies desired state and prune removes resources no longer present in desired state.',
  'OIDC em vez de credencial estática': 'OIDC instead of static credentials',
  'O workflow troca um token OIDC por credenciais temporárias e limitadas no provedor.': 'The workflow exchanges an OIDC token for temporary, scoped credentials from the provider.',

  // AWS
  'IAM: principal assume role e recebe credenciais temporárias': 'IAM: a principal assumes a role and receives temporary credentials',
  'Uma role contém uma trust policy que define quem pode assumi-la e permission policies que definem o que as credenciais temporárias podem fazer. Aplicações devem usar roles associadas ao runtime em vez de access keys estáticas.': 'A role contains a trust policy defining who may assume it and permission policies defining what the temporary credentials can do. Applications should use roles associated with their runtime instead of static access keys.',
  'S3 privado com IAM role e VPC endpoint': 'Private S3 with an IAM role and VPC endpoint',
  'O workload recebe credenciais temporárias por uma IAM role. A identity policy concede as ações S3 necessárias; a bucket policy pode restringir principals/condições e é essencial em cenários cross-account. Um Gateway VPC Endpoint permite acesso privado ao S3 sem NAT/Internet Gateway.': 'The workload receives temporary credentials from an IAM role. The identity policy grants the required S3 actions; the bucket policy can restrict principals and conditions and is essential in cross-account scenarios. A Gateway VPC Endpoint provides private S3 access without a NAT or Internet Gateway.',
  'RDS Multi-AZ em subnets privadas': 'RDS Multi-AZ in private subnets',
  'A aplicação acessa o endpoint RDS em subnets privadas. Em Multi-AZ, a AWS mantém uma réplica standby em outra AZ para alta disponibilidade. Read Replica é uma funcionalidade distinta, usada principalmente para escalar leituras.': 'The application reaches the RDS endpoint through private subnets. With Multi-AZ, AWS maintains a standby replica in another AZ for high availability. A Read Replica is a separate feature used primarily to scale reads.',
  'Lambda: event source, execution role e VPC opcional': 'Lambda: event source, execution role, and optional VPC',
  'A execution role autoriza a função a chamar APIs AWS. Ao conectar Lambda a uma VPC, a função ganha acesso aos recursos privados dessa VPC; saída para Internet precisa ser projetada, por exemplo via NAT, enquanto VPC endpoints podem fornecer acesso privado a serviços AWS suportados.': 'The execution role authorizes the function to call AWS APIs. Connecting Lambda to a VPC gives it access to private VPC resources; Internet egress must be designed, for example through NAT, while VPC endpoints can provide private access to supported AWS services.',
  'ECS/Fargate: execution role versus task role': 'ECS/Fargate: execution role versus task role',
  'A task execution role é usada pelo ECS/Fargate para operações de infraestrutura como pull de imagem e envio de logs. A task role é entregue ao código da aplicação dentro do task e deve conter permissões de negócio, por exemplo acesso a S3 ou SQS.': 'The task execution role is used by ECS/Fargate for infrastructure operations such as pulling images and sending logs. The task role is delivered to application code inside the task and should contain business permissions such as access to S3 or SQS.',
  'EKS: managed control plane, data plane e IAM por workload': 'EKS: managed control plane, data plane, and IAM per workload',
  'O EKS gerencia o Kubernetes control plane. Pods executam em EC2 managed node groups ou Fargate. Permissões AWS da aplicação devem ser entregues ao Pod por EKS Pod Identity ou IRSA, evitando concentrar acesso de aplicação no node IAM role.': 'EKS manages the Kubernetes control plane. Pods run on EC2 managed node groups or Fargate. Application AWS permissions should be delivered to the Pod through EKS Pod Identity or IRSA instead of concentrating application access in the node IAM role.',
  'SNS + SQS: fan-out assíncrono e consumidores independentes': 'SNS + SQS: asynchronous fan-out and independent consumers',
  'SNS publica uma mensagem para múltiplas subscriptions. Filas SQS desacoplam cada consumidor, absorvem picos e permitem retries. Uma DLQ recebe mensagens que excedem a política de redrive configurada.': 'SNS publishes a message to multiple subscriptions. SQS queues decouple each consumer, absorb spikes, and support retries. A DLQ receives messages that exceed the configured redrive policy.',
  'VPC: subnets públicas e privadas com entrada e saída controladas': 'VPC: public and private subnets with controlled ingress and egress',
  'Uma subnet é pública quando sua route table possui rota para um Internet Gateway e o recurso possui endereçamento/configuração compatível. Workloads privados podem iniciar conexões IPv4 para a Internet via NAT Gateway em subnet pública, sem aceitar conexões de entrada iniciadas pela Internet.': 'A subnet is public when its route table has a route to an Internet Gateway and the resource has compatible addressing/configuration. Private workloads can initiate IPv4 connections to the Internet through a NAT Gateway in a public subnet without accepting Internet-initiated inbound connections.',
  'Conectividade híbrida: VPCs, Transit Gateway, VPN e Direct Connect': 'Hybrid connectivity: VPCs, Transit Gateway, VPN, and Direct Connect',
  'Para múltiplas VPCs e redes on-premises, Transit Gateway pode atuar como hub de roteamento. Site-to-Site VPN fornece túneis IPsec sobre a Internet; Direct Connect fornece conectividade dedicada. Rotas de ida e retorno e CIDRs não sobrepostos continuam essenciais.': 'For multiple VPCs and on-premises networks, Transit Gateway can act as a routing hub. Site-to-Site VPN provides IPsec tunnels over the Internet; Direct Connect provides dedicated connectivity. Forward and return routes and non-overlapping CIDRs remain essential.',
  'AWS Site-to-Site VPN: dois túneis entre AWS e customer gateway': 'AWS Site-to-Site VPN: two tunnels between AWS and the customer gateway',
  'Uma Site-to-Site VPN conecta o customer gateway on-premises a um Virtual Private Gateway ou Transit Gateway. A conexão inclui dois túneis para redundância; BGP é usado quando a configuração dinâmica é selecionada e o equipamento suporta.': 'A Site-to-Site VPN connects the on-premises customer gateway to a Virtual Private Gateway or Transit Gateway. The connection includes two tunnels for redundancy; BGP is used when dynamic routing is selected and the device supports it.',
  'Security Group versus Network ACL': 'Security Group versus Network ACL',
  'NACL atua no limite da subnet; Security Group atua junto à interface/recurso. A natureza stateful versus stateless muda como regras de retorno são tratadas.': 'A NACL operates at the subnet boundary; a Security Group operates at the network interface/resource. Stateful versus stateless behavior changes how return traffic rules are handled.',
  'Aplicação Multi-AZ com ALB, compute e RDS Multi-AZ': 'Multi-AZ application with ALB, compute, and RDS Multi-AZ',
  'O tráfego entra por um ALB e pode ser atendido por workloads em duas AZs; o banco mantém primary e standby em AZs distintas.': 'Traffic enters through an ALB and can be served by workloads in two AZs; the database maintains primary and standby instances in different AZs.',

  // Common node and edge labels
  'Cliente': 'Client', 'Clientes': 'Clients', 'Rede A': 'Network A', 'Rede B': 'Network B',
  'Sintoma\n"não conecta"': 'Symptom\n"cannot connect"', '1. Prefixos\nsem overlap': '1. Prefixes\nno overlap',
  '2. Conectividade L3\nrouter / peering / VPN': '2. L3 connectivity\nrouter / peering / VPN',
  '3. Rotas\nida + retorno': '3. Routes\nforward + return', '5. Validar\nping · traceroute · tcpdump': '5. Validate\nping · traceroute · tcpdump',
  'Authentication\nQuem é?': 'Authentication\nWho are you?', 'Authorization\nPode fazer?': 'Authorization\nIs it allowed?',
  'Admission\nÉ permitido / mutado?': 'Admission\nAllowed / mutated?', 'Quorum = 2 de 3': 'Quorum = 2 of 3',
  'Requisito do workload': 'Workload requirement', 'Réplicas intercambiáveis': 'Interchangeable replicas',
  'Identidade / storage estável': 'Stable identity / storage', 'Uma cópia por node': 'One copy per node',
  'readinessProbe falha': 'readinessProbe fails', 'Service não envia\ntráfego normal': 'Service does not send\nnormal traffic',
  'Credenciais\ntemporárias': 'Temporary\ncredentials', 'Trust policy\nQuem pode assumir?': 'Trust policy\nWho can assume it?',
  'Permission policy\nO que pode fazer?': 'Permission policy\nWhat can it do?',
  'atualiza condição': 'updates condition', 'persistência': 'persistence', 'identidade/estado': 'identity/state',
  'identidade': 'identity', 'executa': 'runs', 'verifica': 'checks', 'rota': 'route', 'estado': 'state',
  'stored data': 'stored data', 'forward path': 'forward path', 'return path': 'return path',
};
