import type { KubernetesIstioDiagramKey } from './kubernetes-istio-diagrams';

export type IstioLocale = 'pt' | 'en';
type Bi = { pt: string; en: string };

export type IstioTopic = {
  id: string;
  title: string;
  group: 'architecture' | 'traffic-security' | 'kserve' | 'alternatives';
  diagram: KubernetesIstioDiagramKey;
  summary: Bi;
  steps: Bi[];
  notes: Bi[];
  code?: string;
};

const b = (pt: string, en: string): Bi => ({ pt, en });

export const istioTopics: IstioTopic[] = [
  {
    id: 'istio-sidecar-architecture', title: 'Istio sidecar architecture', group: 'architecture', diagram: 'sidecar',
    summary: b('Istio separa control plane e data plane. Istiod mantém discovery, configuração e identidade; Envoy sidecars interceptam o tráfego de cada workload sem exigir que a aplicação implemente mTLS, retries, routing ou telemetria.', 'Istio separates the control plane from the data plane. Istiod maintains discovery, configuration, and identity; Envoy sidecars intercept workload traffic without requiring the application to implement mTLS, retries, routing, or telemetry.'),
    steps: [b('O operador cria recursos Kubernetes/Istio, como Gateway, VirtualService, DestinationRule e policies.', 'The operator creates Kubernetes/Istio resources such as Gateway, VirtualService, DestinationRule, and policies.'), b('Istiod observa o cluster, converte configuração de alto nível em configuração do proxy e distribui-a via xDS.', 'Istiod observes the cluster, converts high-level configuration into proxy configuration, and distributes it through xDS.'), b('Istiod também entrega identidade e certificados de workload para comunicação segura.', 'Istiod also delivers workload identity and certificates for secure communication.'), b('O tráfego outbound do Pod A é capturado pelo Envoy local.', 'Pod A outbound traffic is captured by the local Envoy.'), b('Os proxies aplicam routing, load balancing, mTLS, policy e telemetria antes de entregar a chamada ao Pod B.', 'The proxies apply routing, load balancing, mTLS, policy, and telemetry before delivering the call to Pod B.')],
    notes: [b('Sidecar mode oferece processamento L7 próximo a cada workload, mas acrescenta um proxy por Pod e aumenta custo operacional/recursos.', 'Sidecar mode provides L7 processing next to every workload, but adds one proxy per Pod and increases operational/resource cost.'), b('Use revisões do control plane em upgrades importantes para reduzir blast radius e permitir canary do próprio Istio.', 'Use control-plane revisions for major upgrades to reduce blast radius and allow canary upgrades of Istio itself.')],
    code: `# avaliação / laboratório\nistioctl install\n\n# habilitar injeção automática\nkubectl label namespace app istio-injection=enabled --overwrite\n\n# verificar\nkubectl get pods -n app\nistioctl proxy-status`,
  },
  {
    id: 'istio-sidecar-injection', title: 'Sidecar injection', group: 'architecture', diagram: 'injection',
    summary: b('Na injeção automática, um mutating admission webhook modifica o Pod na criação. O Deployment não precisa conter manualmente o container istio-proxy.', 'With automatic injection, a mutating admission webhook modifies the Pod at creation time. The Deployment does not need to contain the istio-proxy container manually.'),
    steps: [b('O namespace ou Pod recebe o label de injeção/revisão.', 'The namespace or Pod receives the injection/revision label.'), b('Ao criar o Pod, o API Server envia um AdmissionReview ao injector.', 'When the Pod is created, the API Server sends an AdmissionReview to the injector.'), b('O webhook devolve um patch com istio-proxy e configuração necessária.', 'The webhook returns a patch containing istio-proxy and required configuration.'), b('O kubelet cria o Pod já mutado; normalmente o READY passa a refletir app + proxy.', 'The kubelet creates the already-mutated Pod; READY normally reflects app + proxy.')],
    notes: [b('Para upgrades controlados, prefira labels de revisão como istio.io/rev=<revision> em vez de trocar todo o mesh simultaneamente.', 'For controlled upgrades, prefer revision labels such as istio.io/rev=<revision> instead of switching the whole mesh at once.'), b('Mudança do label não injeta retroativamente Pods existentes: recrie/rollout os workloads.', 'Changing the label does not retroactively inject existing Pods: recreate/roll out the workloads.')],
    code: `kubectl label namespace app istio-injection=enabled --overwrite\nkubectl rollout restart deployment -n app\nkubectl get pod -n app -o jsonpath='{range .items[*]}{.metadata.name}{" => "}{.spec.containers[*].name}{"\\n"}{end}'`,
  },
  {
    id: 'istio-ambient', title: 'Ambient mesh: ztunnel + waypoint', group: 'architecture', diagram: 'ambient',
    summary: b('Ambient mode retira o sidecar dos Pods e divide capacidades em duas camadas: ztunnel por Node para segurança/conectividade L4 e waypoint Envoy opcional para políticas e tráfego L7.', 'Ambient mode removes sidecars from Pods and splits capabilities into two layers: per-node ztunnel for L4 security/connectivity and an optional Envoy waypoint for L7 policy and traffic management.'),
    steps: [b('O namespace entra no mesh ambient.', 'The namespace joins the ambient mesh.'), b('O Istio CNI redireciona tráfego do workload para o ztunnel do Node.', 'Istio CNI redirects workload traffic to the node ztunnel.'), b('ztunnel cria o secure overlay L4, autentica workloads e usa mTLS/HBONE.', 'ztunnel creates the L4 secure overlay, authenticates workloads, and uses mTLS/HBONE.'), b('Quando há necessidade de HTTP routing, L7 authorization, retries, tracing ou outras funções L7, o tráfego passa por um waypoint.', 'When HTTP routing, L7 authorization, retries, tracing, or other L7 functions are required, traffic passes through a waypoint.'), b('O ztunnel do destino entrega a conexão ao workload sem sidecar.', 'The destination ztunnel delivers the connection to the workload without a sidecar.')],
    notes: [b('Ambient permite adoção incremental: L4 seguro primeiro e L7 somente onde necessário.', 'Ambient enables incremental adoption: secure L4 first and L7 only where required.'), b('Sidecar e ambient podem coexistir no mesmo mesh durante migração.', 'Sidecar and ambient can coexist in the same mesh during migration.')],
    code: `# depois de instalar Istio com suporte ambient\nkubectl label namespace app istio.io/dataplane-mode=ambient\n\n# criar waypoint L7 quando necessário\nistioctl waypoint apply -n app --enroll-namespace\n\nistioctl ztunnel-config workloads`,
  },
  {
    id: 'istio-traffic-management', title: 'Traffic management and canary', group: 'traffic-security', diagram: 'traffic',
    summary: b('Istio desacopla o endereço usado pelo cliente da versão real que recebe o request. VirtualService/HTTPRoute escolhe rotas; DestinationRule define subsets e policies por destino.', 'Istio decouples the address used by the client from the real version receiving the request. VirtualService/HTTPRoute selects routes; DestinationRule defines subsets and per-destination policies.'),
    steps: [b('O cliente acessa o ingress Gateway ou um Service interno.', 'The client accesses the ingress Gateway or an internal Service.'), b('A regra L7 avalia host, URI, headers ou outras condições.', 'The L7 rule evaluates host, URI, headers, or other conditions.'), b('A rota escolhe um subset e pode dividir tráfego por peso, por exemplo 90% v1 / 10% v2.', 'The route selects a subset and can split traffic by weight, for example 90% v1 / 10% v2.'), b('DestinationRule aplica load balancing, connection pool, TLS, outlier detection e circuit breaker.', 'DestinationRule applies load balancing, connection pool, TLS, outlier detection, and circuit breaking.'), b('O proxy encaminha a request ao endpoint saudável selecionado.', 'The proxy forwards the request to the selected healthy endpoint.')],
    notes: [b('Retries sem deadline/retry budget podem amplificar overload. Configure timeout, retry count e backoff de acordo com o SLO.', 'Retries without a deadline/retry budget can amplify overload. Configure timeout, retry count, and backoff according to the SLO.'), b('Fault injection é útil para testar resiliência, mas deve ser limitado a ambientes/rotas controlados.', 'Fault injection is useful for resilience testing but should be limited to controlled environments/routes.')],
    code: `apiVersion: networking.istio.io/v1\nkind: VirtualService\nmetadata:\n  name: reviews\nspec:\n  hosts: [reviews]\n  http:\n  - timeout: 2s\n    retries:\n      attempts: 2\n      perTryTimeout: 700ms\n    route:\n    - destination: { host: reviews, subset: v1 }\n      weight: 90\n    - destination: { host: reviews, subset: v2 }\n      weight: 10\n---\napiVersion: networking.istio.io/v1\nkind: DestinationRule\nmetadata:\n  name: reviews\nspec:\n  host: reviews\n  subsets:\n  - name: v1\n    labels: { version: v1 }\n  - name: v2\n    labels: { version: v2 }`,
  },
  {
    id: 'istio-security', title: 'mTLS, identity, JWT and AuthorizationPolicy', group: 'traffic-security', diagram: 'security',
    summary: b('Istio adiciona identidade de workload e policy enforcement transparente. mTLS protege workload-to-workload; JWT/OIDC trata identidade do utilizador; AuthorizationPolicy controla acesso.', 'Istio adds workload identity and transparent policy enforcement. mTLS protects workload-to-workload traffic; JWT/OIDC handles end-user identity; AuthorizationPolicy controls access.'),
    steps: [b('Istiod/CA emite certificados curtos para as identidades dos workloads.', 'Istiod/CA issues short-lived certificates for workload identities.'), b('PeerAuthentication pode exigir STRICT mTLS no mesh, namespace ou workload.', 'PeerAuthentication can require STRICT mTLS at mesh, namespace, or workload scope.'), b('Os proxies autenticam mutuamente as identidades no handshake TLS.', 'The proxies mutually authenticate identities during the TLS handshake.'), b('RequestAuthentication valida JWT quando a API recebe identidade de utilizador.', 'RequestAuthentication validates JWT when the API receives end-user identity.'), b('AuthorizationPolicy aplica ALLOW/DENY/CUSTOM usando principal, namespace, método, path e claims.', 'AuthorizationPolicy applies ALLOW/DENY/CUSTOM using principal, namespace, method, path, and claims.')],
    notes: [b('Adote default-deny por namespace/workload e abra apenas fluxos necessários.', 'Adopt default-deny by namespace/workload and open only required flows.'), b('NetworkPolicy continua útil: Istio policy não substitui controles CNI/L3-L4 de defesa em profundidade.', 'NetworkPolicy remains useful: Istio policy does not replace CNI/L3-L4 controls in a defense-in-depth design.')],
    code: `apiVersion: security.istio.io/v1\nkind: PeerAuthentication\nmetadata:\n  name: default\n  namespace: app\nspec:\n  mtls:\n    mode: STRICT\n---\napiVersion: security.istio.io/v1\nkind: AuthorizationPolicy\nmetadata:\n  name: allow-frontend\n  namespace: app\nspec:\n  selector:\n    matchLabels: { app: api }\n  rules:\n  - from:\n    - source:\n        principals: ["cluster.local/ns/app/sa/frontend"]\n    to:\n    - operation:\n        methods: ["GET", "POST"]`,
  },
  {
    id: 'istio-observability', title: 'Metrics, logs, traces and Kiali', group: 'traffic-security', diagram: 'telemetry',
    summary: b('Como o proxy vê o tráfego, pode gerar telemetria de serviço sem instrumentar cada aplicação para métricas básicas de rede. Tracing distribuído ainda depende de propagação correta de contexto pela aplicação.', 'Because the proxy sees traffic, it can generate service telemetry without instrumenting every application for basic network metrics. Distributed tracing still depends on correct context propagation by the application.'),
    steps: [b('Envoy/waypoint/ztunnel observa requests e conexões.', 'Envoy/waypoint/ztunnel observes requests and connections.'), b('Telemetry API define métricas, access logs e tracing por mesh, namespace ou workload.', 'Telemetry API defines metrics, access logs, and tracing at mesh, namespace, or workload scope.'), b('Prometheus coleta métricas; OpenTelemetry pode receber logs/traces.', 'Prometheus collects metrics; OpenTelemetry can receive logs/traces.'), b('Grafana, Jaeger e Kiali tornam os sinais navegáveis para operação e troubleshooting.', 'Grafana, Jaeger, and Kiali make the signals navigable for operations and troubleshooting.')],
    notes: [b('Controle cardinalidade e sampling para evitar custo excessivo.', 'Control cardinality and sampling to avoid excessive cost.'), b('Kiali é especialmente útil para visualizar o service graph e validar mTLS/policies, mas não substitui métricas/logs/traces como fontes de diagnóstico.', 'Kiali is particularly useful for visualizing the service graph and validating mTLS/policies, but it does not replace metrics/logs/traces as diagnostic signals.')],
    code: `apiVersion: telemetry.istio.io/v1\nkind: Telemetry\nmetadata:\n  name: mesh-default\n  namespace: istio-system\nspec:\n  accessLogging:\n  - providers:\n    - name: envoy\n  metrics:\n  - providers:\n    - name: prometheus`,
  },
  {
    id: 'istio-egress', title: 'Ingress, egress and external dependencies', group: 'traffic-security', diagram: 'egress',
    summary: b('Ingress controla entrada no mesh; egress controla saída. ServiceEntry adiciona uma dependência externa ao registry lógico e um Egress Gateway pode centralizar o caminho de saída.', 'Ingress controls traffic entering the mesh; egress controls traffic leaving it. ServiceEntry adds an external dependency to the logical registry and an Egress Gateway can centralize the outbound path.'),
    steps: [b('Ingress Gateway termina/encaminha tráfego externo conforme Gateway + route.', 'Ingress Gateway terminates/routes external traffic according to Gateway + route.'), b('Workloads que chamam APIs externas podem declarar a dependência com ServiceEntry.', 'Workloads calling external APIs can declare the dependency with ServiceEntry.'), b('Policy pode forçar determinados destinos a passar por Egress Gateway.', 'Policy can force selected destinations through an Egress Gateway.'), b('No gateway, a equipa pode aplicar TLS origination, auditoria, allow-list e controles de firewall/NAT.', 'At the gateway, the team can apply TLS origination, auditing, allow lists, and firewall/NAT controls.')],
    notes: [b('Não assuma que ServiceEntry por si só é um firewall; combine com egress policy/CNI/firewall conforme o threat model.', 'Do not assume ServiceEntry alone is a firewall; combine it with egress policy/CNI/firewall according to the threat model.')],
    code: `apiVersion: networking.istio.io/v1\nkind: ServiceEntry\nmetadata:\n  name: payments-external\nspec:\n  hosts: [api.example.com]\n  ports:\n  - number: 443\n    name: https\n    protocol: HTTPS\n  resolution: DNS\n  location: MESH_EXTERNAL`,
  },
  {
    id: 'istio-kserve', title: 'KServe + Istio model-serving architecture', group: 'kserve', diagram: 'kserve',
    summary: b('Este fluxo adapta a arquitetura da imagem anexada ao padrão atual de KServe: o CR InferenceService é reconciliado, o runtime/container e o modelo são obtidos, e Istio pode fornecer ingress, TLS/mTLS, routing, authorization e telemetria para a API de inferência.', 'This flow adapts the attached architecture to the current KServe model: the InferenceService CR is reconciled, the runtime/container and model are obtained, and Istio can provide ingress, TLS/mTLS, routing, authorization, and telemetry for the inference API.'),
    steps: [b('O utilizador/plataforma cria um InferenceService com runtime/model format e storage URI.', 'The user/platform creates an InferenceService with runtime/model format and storage URI.'), b('O KServe Controller observa o CR e reconcilia o estado desejado.', 'The KServe Controller watches the CR and reconciles desired state.'), b('KServe seleciona ServingRuntime/ClusterServingRuntime e cria recursos Kubernetes, como Deployment, Service, networking e autoscaling conforme o modo.', 'KServe selects a ServingRuntime/ClusterServingRuntime and creates Kubernetes resources such as Deployment, Service, networking, and autoscaling according to deployment mode.'), b('O runtime image é obtido do container registry.', 'The runtime image is pulled from the container registry.'), b('storage-initializer/modelcar/PVC disponibiliza o model artifact para o model server.', 'storage-initializer/modelcar/PVC makes the model artifact available to the model server.'), b('O model server carrega o modelo e expõe o protocolo de inferência HTTP/gRPC.', 'The model server loads the model and exposes the HTTP/gRPC inference protocol.'), b('O cliente entra pelo Gateway/Ingress; Istio aplica TLS, routing, autenticação/autorização e telemetria.', 'The client enters through Gateway/Ingress; Istio applies TLS, routing, authentication/authorization, and telemetry.'), b('Dentro do mesh, comunicação com transformer/explainer/outros serviços pode usar mTLS e policies de identidade.', 'Inside the mesh, communication with transformers/explainers/other services can use mTLS and identity policies.')],
    notes: [b('No KServe atual, Standard Mode usa Deployments Kubernetes e Gateway API é uma opção recomendada; Istio ingress é uma integração suportada, mas não é obrigatório em todo Standard Mode.', 'In current KServe, Standard Mode uses Kubernetes Deployments and Gateway API is a recommended option; Istio ingress is supported but is not mandatory for every Standard Mode deployment.'), b('Em Knative mode, Istio continua sendo uma opção recomendada de networking, com autoscaling/serverless fornecido pela camada Knative.', 'In Knative mode, Istio remains a recommended networking option, with serverless/autoscaling provided by the Knative layer.')],
    code: `apiVersion: serving.kserve.io/v1beta1\nkind: InferenceService\nmetadata:\n  name: fraud-model\n  namespace: ml\nspec:\n  predictor:\n    model:\n      modelFormat:\n        name: sklearn\n      storageUri: s3://ml-models/fraud/1\n      resources:\n        requests:\n          cpu: "500m"\n          memory: 1Gi`,
  },
  {
    id: 'istio-alternatives', title: 'Alternatives to Istio', group: 'alternatives', diagram: 'alternatives',
    summary: b('Nem toda plataforma precisa de Istio. A decisão deve começar pelos requisitos de identidade, L7 routing, observabilidade, multi-cluster, egress e custo operacional.', 'Not every platform needs Istio. The decision should start from identity, L7 routing, observability, multi-cluster, egress, and operational-cost requirements.'),
    steps: [b('Linkerd: service mesh Kubernetes com control plane e micro-proxies sidecar, normalmente escolhido quando simplicidade operacional e footprint do proxy são prioridades.', 'Linkerd: Kubernetes service mesh with a control plane and sidecar micro-proxies, commonly chosen when operational simplicity and proxy footprint are priorities.'), b('Cilium Service Mesh: usa eBPF para L3/L4 e Envoy onde há necessidade L7; faz sentido quando Cilium já é o CNI/dataplane e a equipa quer reduzir camadas de networking.', 'Cilium Service Mesh: uses eBPF for L3/L4 and Envoy where L7 is required; it makes sense when Cilium is already the CNI/dataplane and the team wants fewer networking layers.'), b('Consul Service Mesh: usa service catalog, CA e Envoy e é forte quando serviços vivem também em VMs, Nomad, ECS ou múltiplos runtimes além de Kubernetes.', 'Consul Service Mesh: uses a service catalog, CA, and Envoy and is strong when services also run on VMs, Nomad, ECS, or multiple runtimes beyond Kubernetes.'), b('Sem mesh completo: Gateway API + CNI/NetworkPolicy + cert-manager/SPIFFE + OpenTelemetry pode ser suficiente quando o requisito é principalmente north-south routing, L3/L4 policy, certificados e observabilidade.', 'Without a full mesh: Gateway API + CNI/NetworkPolicy + cert-manager/SPIFFE + OpenTelemetry can be enough when the requirement is mainly north-south routing, L3/L4 policy, certificates, and observability.')],
    notes: [b('Evite escolher service mesh apenas por moda. Se poucas aplicações precisam de L7 policy/mTLS automático, o custo de operação pode superar o benefício.', 'Avoid choosing a service mesh because it is fashionable. If only a few applications need L7 policy/automatic mTLS, operational cost can outweigh the benefit.'), b('Avalie também maturidade da equipa, debugging, upgrades, latency overhead, resource overhead e integração com o CNI/cloud existente.', 'Also evaluate team maturity, debugging, upgrades, latency overhead, resource overhead, and integration with the existing CNI/cloud.')],
  },
];

export const istioGroups = [
  { id: 'architecture', pt: 'Arquitetura Istio', en: 'Istio architecture' },
  { id: 'traffic-security', pt: 'Tráfego, segurança e observabilidade', en: 'Traffic, security, and observability' },
  { id: 'kserve', pt: 'KServe + Istio', en: 'KServe + Istio' },
  { id: 'alternatives', pt: 'Alternativas ao Istio', en: 'Istio alternatives' },
] as const;
