import type { DiagramSpec } from './diagrams';

type SecurityDiagramKey = 'tls' | 'firewall' | 'proxy' | 'identity';

const sources = {
  tls: { label: 'RFC 9846 — TLS 1.3', url: 'https://www.rfc-editor.org/rfc/rfc9846' },
  http: { label: 'RFC 9110 — HTTP Semantics', url: 'https://www.rfc-editor.org/rfc/rfc9110' },
  firewall: { label: 'NIST SP 800-41 Rev. 1 — Firewalls and Firewall Policy', url: 'https://csrc.nist.gov/pubs/sp/800/41/r1/final' },
  zeroTrust: { label: 'NIST SP 800-207 — Zero Trust Architecture', url: 'https://csrc.nist.gov/pubs/sp/800/207/final' },
  oauth: { label: 'RFC 6749 — OAuth 2.0', url: 'https://www.rfc-editor.org/rfc/rfc6749' },
  oidc: { label: 'OpenID Connect Core 1.0', url: 'https://openid.net/specs/openid-connect-core-1_0.html' },
};

const pt: Record<SecurityDiagramKey, DiagramSpec> = {
  tls: {
    title: 'TLS 1.3: autenticação, negociação de chaves e canal cifrado',
    description: 'O handshake autentica normalmente o servidor por certificado, negocia material criptográfico efêmero e deriva chaves de tráfego. Depois do Finished, os dados de aplicação seguem protegidos por chaves simétricas derivadas para a sessão.',
    width: 1120,
    height: 500,
    nodes: [
      { id: 'client', label: 'Cliente\nBrowser / API client', x: 30, y: 180, width: 190, kind: 'client' },
      { id: 'ch', label: 'ClientHello\nversions · key share · SNI · ALPN', x: 270, y: 55, width: 230, height: 72, kind: 'control' },
      { id: 'server', label: 'Servidor TLS', x: 865, y: 180, width: 190, kind: 'workload' },
      { id: 'sh', label: 'ServerHello\nselected key share', x: 595, y: 55, width: 220, kind: 'control' },
      { id: 'cert', label: 'Certificate + CertificateVerify\nprova de identidade', x: 570, y: 190, width: 270, height: 72, kind: 'security' },
      { id: 'pki', label: 'PKI / Trust Store\nCA · hostname · validade', x: 270, y: 280, width: 230, height: 72, kind: 'security' },
      { id: 'keys', label: 'Handshake Finished\nchaves de tráfego derivadas', x: 570, y: 330, width: 270, height: 72, kind: 'security' },
      { id: 'app', label: 'Application Data\nHTTPS / HTTP/2 / HTTP/3 semantics', x: 270, y: 410, width: 280, kind: 'data' },
    ],
    edges: [
      { from: 'client', to: 'ch', label: '1. inicia', animated: true },
      { from: 'ch', to: 'sh', label: 'negocia parâmetros', animated: true },
      { from: 'sh', to: 'server', label: '2. seleção' },
      { from: 'server', to: 'cert', label: '3. identidade' },
      { from: 'cert', to: 'pki', label: 'validar cadeia + nome' },
      { from: 'pki', to: 'client', label: 'trusted / rejected' },
      { from: 'cert', to: 'keys', label: 'Finished' },
      { from: 'client', to: 'keys', label: 'client Finished' },
      { from: 'keys', to: 'app', label: 'canal cifrado', animated: true },
      { from: 'app', to: 'server', label: 'dados protegidos', animated: true },
    ],
    sources: [sources.tls],
  },
  firewall: {
    title: 'Firewall stateful: zonas, política e estado de conexão',
    description: 'Um firewall de rede decide permitir ou negar tráfego com base em interfaces/zonas, endereços, protocolos, portas e estado. Em firewalls stateful, o tráfego de retorno de uma conexão permitida pode ser reconhecido pela state table sem exigir uma regra independente simétrica.',
    width: 1120,
    height: 500,
    nodes: [
      { id: 'internet', label: 'Internet\nUntrusted zone', x: 30, y: 180, width: 180, kind: 'network' },
      { id: 'edge', label: 'Edge Firewall\nL3/L4 policy', x: 275, y: 180, width: 200, height: 72, kind: 'security' },
      { id: 'state', label: 'State Table\nsrc/dst · ports · protocol · state', x: 275, y: 330, width: 230, height: 78, kind: 'data' },
      { id: 'dmz', label: 'DMZ\nReverse Proxy / WAF', x: 570, y: 70, width: 220, kind: 'security' },
      { id: 'appfw', label: 'Internal Firewall\nsegmentation policy', x: 570, y: 240, width: 220, kind: 'security' },
      { id: 'app', label: 'Application Tier', x: 865, y: 240, width: 190, kind: 'workload' },
      { id: 'db', label: 'Database Tier', x: 865, y: 370, width: 190, kind: 'data' },
      { id: 'deny', label: 'Default deny / least exposure', x: 570, y: 405, width: 220, kind: 'decision' },
    ],
    edges: [
      { from: 'internet', to: 'edge', label: 'new flow', animated: true },
      { from: 'edge', to: 'state', label: 'track allowed session' },
      { from: 'edge', to: 'dmz', label: 'HTTPS 443 allowed', animated: true },
      { from: 'dmz', to: 'appfw', label: 'approved backend flow' },
      { from: 'appfw', to: 'app', label: 'policy match', animated: true },
      { from: 'app', to: 'db', label: 'DB port only' },
      { from: 'deny', to: 'edge', label: 'everything else' },
      { from: 'deny', to: 'appfw', label: 'everything else' },
    ],
    sources: [sources.firewall, sources.zeroTrust],
  },
  proxy: {
    title: 'Forward proxy versus reverse proxy',
    description: 'O forward proxy representa clientes ao acessar destinos externos. O reverse proxy representa servidores perante clientes externos e pode terminar TLS, aplicar políticas, balancear tráfego e ocultar a topologia dos backends.',
    width: 1160,
    height: 520,
    nodes: [
      { id: 'clientA', label: 'Cliente interno', x: 30, y: 80, width: 170, kind: 'client' },
      { id: 'forward', label: 'Forward Proxy\ncontrole de egress', x: 270, y: 80, width: 210, height: 72, kind: 'security' },
      { id: 'internet', label: 'Internet', x: 550, y: 80, width: 170, kind: 'network' },
      { id: 'external', label: 'Servidor externo', x: 850, y: 80, width: 190, kind: 'workload' },
      { id: 'clientB', label: 'Cliente externo', x: 30, y: 335, width: 170, kind: 'client' },
      { id: 'reverse', label: 'Reverse Proxy\nTLS · routing · LB · policy', x: 270, y: 320, width: 230, height: 82, kind: 'security' },
      { id: 'api1', label: 'Backend API 1', x: 650, y: 275, width: 180, kind: 'workload' },
      { id: 'api2', label: 'Backend API 2', x: 650, y: 390, width: 180, kind: 'workload' },
      { id: 'private', label: 'Rede privada\nbackends não expostos', x: 900, y: 335, width: 210, height: 72, kind: 'network' },
    ],
    edges: [
      { from: 'clientA', to: 'forward', label: 'request outbound', animated: true },
      { from: 'forward', to: 'internet', label: 'proxy request', animated: true },
      { from: 'internet', to: 'external', label: 'destination' },
      { from: 'clientB', to: 'reverse', label: 'public request', animated: true },
      { from: 'reverse', to: 'api1', label: 'route / load balance', animated: true },
      { from: 'reverse', to: 'api2', label: 'route / load balance', animated: true },
      { from: 'api1', to: 'private' }, { from: 'api2', to: 'private' },
    ],
    sources: [sources.http, sources.tls],
  },
  identity: {
    title: 'Identity: autenticação, tokens, policy e acesso ao recurso',
    description: 'Identidade moderna separa autenticação de autorização. Um IdP autentica o utilizador ou workload; tokens e claims carregam contexto; um Policy Enforcement Point consulta/aplica política antes de permitir acesso ao recurso. Zero Trust exige decisões contínuas baseadas em identidade e contexto, não apenas localização de rede.',
    width: 1160,
    height: 520,
    nodes: [
      { id: 'principal', label: 'Principal\nUser / Workload', x: 25, y: 185, width: 190, height: 72, kind: 'client' },
      { id: 'idp', label: 'Identity Provider\nMFA · federation · workload identity', x: 275, y: 65, width: 250, height: 82, kind: 'security' },
      { id: 'token', label: 'Token / Credential\nissuer · subject · audience · scope', x: 275, y: 300, width: 250, height: 82, kind: 'data' },
      { id: 'pep', label: 'Policy Enforcement Point\nAPI Gateway / proxy / service', x: 615, y: 185, width: 250, height: 82, kind: 'security' },
      { id: 'pdp', label: 'Policy Decision Point\nRBAC / ABAC / context', x: 615, y: 350, width: 250, height: 82, kind: 'decision' },
      { id: 'resource', label: 'Protected Resource\nAPI · data · infrastructure', x: 930, y: 185, width: 210, height: 82, kind: 'workload' },
    ],
    edges: [
      { from: 'principal', to: 'idp', label: 'authenticate', animated: true },
      { from: 'idp', to: 'token', label: 'issue short-lived credential' },
      { from: 'token', to: 'principal', label: 'credential' },
      { from: 'principal', to: 'pep', label: 'request + credential', animated: true },
      { from: 'pep', to: 'pdp', label: 'identity + claims + context' },
      { from: 'pdp', to: 'pep', label: 'allow / deny' },
      { from: 'pep', to: 'resource', label: 'authorized request', animated: true },
    ],
    sources: [sources.zeroTrust, sources.oauth, sources.oidc],
  },
};

const en: Record<SecurityDiagramKey, DiagramSpec> = {
  tls: {
    ...pt.tls,
    title: 'TLS 1.3: authentication, key establishment, and encrypted channel',
    description: 'The handshake normally authenticates the server with a certificate, negotiates ephemeral cryptographic key material, and derives traffic keys. After Finished, application data is protected with symmetric session keys.',
    nodes: [
      { id: 'client', label: 'Client\nBrowser / API client', x: 30, y: 180, width: 190, kind: 'client' },
      { id: 'ch', label: 'ClientHello\nversions · key share · SNI · ALPN', x: 270, y: 55, width: 230, height: 72, kind: 'control' },
      { id: 'server', label: 'TLS Server', x: 865, y: 180, width: 190, kind: 'workload' },
      { id: 'sh', label: 'ServerHello\nselected key share', x: 595, y: 55, width: 220, kind: 'control' },
      { id: 'cert', label: 'Certificate + CertificateVerify\nidentity proof', x: 570, y: 190, width: 270, height: 72, kind: 'security' },
      { id: 'pki', label: 'PKI / Trust Store\nCA · hostname · validity', x: 270, y: 280, width: 230, height: 72, kind: 'security' },
      { id: 'keys', label: 'Handshake Finished\nderived traffic keys', x: 570, y: 330, width: 270, height: 72, kind: 'security' },
      { id: 'app', label: 'Application Data\nHTTPS / HTTP/2 / HTTP/3 semantics', x: 270, y: 410, width: 280, kind: 'data' },
    ],
    edges: [
      { from: 'client', to: 'ch', label: '1. start', animated: true }, { from: 'ch', to: 'sh', label: 'negotiate parameters', animated: true },
      { from: 'sh', to: 'server', label: '2. selection' }, { from: 'server', to: 'cert', label: '3. identity' },
      { from: 'cert', to: 'pki', label: 'validate chain + name' }, { from: 'pki', to: 'client', label: 'trusted / rejected' },
      { from: 'cert', to: 'keys', label: 'Finished' }, { from: 'client', to: 'keys', label: 'client Finished' },
      { from: 'keys', to: 'app', label: 'encrypted channel', animated: true }, { from: 'app', to: 'server', label: 'protected data', animated: true },
    ],
  },
  firewall: {
    ...pt.firewall,
    title: 'Stateful firewall: zones, policy, and connection state',
    description: 'A network firewall permits or denies traffic based on zones/interfaces, addresses, protocols, ports, and state. A stateful firewall can recognize return traffic for an allowed connection through its state table.',
    nodes: [
      { id: 'internet', label: 'Internet\nUntrusted zone', x: 30, y: 180, width: 180, kind: 'network' },
      { id: 'edge', label: 'Edge Firewall\nL3/L4 policy', x: 275, y: 180, width: 200, height: 72, kind: 'security' },
      { id: 'state', label: 'State Table\nsrc/dst · ports · protocol · state', x: 275, y: 330, width: 230, height: 78, kind: 'data' },
      { id: 'dmz', label: 'DMZ\nReverse Proxy / WAF', x: 570, y: 70, width: 220, kind: 'security' },
      { id: 'appfw', label: 'Internal Firewall\nsegmentation policy', x: 570, y: 240, width: 220, kind: 'security' },
      { id: 'app', label: 'Application Tier', x: 865, y: 240, width: 190, kind: 'workload' },
      { id: 'db', label: 'Database Tier', x: 865, y: 370, width: 190, kind: 'data' },
      { id: 'deny', label: 'Default deny / least exposure', x: 570, y: 405, width: 220, kind: 'decision' },
    ],
    edges: [
      { from: 'internet', to: 'edge', label: 'new flow', animated: true }, { from: 'edge', to: 'state', label: 'track allowed session' },
      { from: 'edge', to: 'dmz', label: 'HTTPS 443 allowed', animated: true }, { from: 'dmz', to: 'appfw', label: 'approved backend flow' },
      { from: 'appfw', to: 'app', label: 'policy match', animated: true }, { from: 'app', to: 'db', label: 'DB port only' },
      { from: 'deny', to: 'edge', label: 'everything else' }, { from: 'deny', to: 'appfw', label: 'everything else' },
    ],
  },
  proxy: {
    ...pt.proxy,
    title: 'Forward proxy versus reverse proxy',
    description: 'A forward proxy represents clients when reaching external destinations. A reverse proxy represents servers to external clients and can terminate TLS, enforce policy, balance traffic, and hide backend topology.',
    nodes: [
      { id: 'clientA', label: 'Internal Client', x: 30, y: 80, width: 170, kind: 'client' },
      { id: 'forward', label: 'Forward Proxy\negress control', x: 270, y: 80, width: 210, height: 72, kind: 'security' },
      { id: 'internet', label: 'Internet', x: 550, y: 80, width: 170, kind: 'network' },
      { id: 'external', label: 'External Server', x: 850, y: 80, width: 190, kind: 'workload' },
      { id: 'clientB', label: 'External Client', x: 30, y: 335, width: 170, kind: 'client' },
      { id: 'reverse', label: 'Reverse Proxy\nTLS · routing · LB · policy', x: 270, y: 320, width: 230, height: 82, kind: 'security' },
      { id: 'api1', label: 'Backend API 1', x: 650, y: 275, width: 180, kind: 'workload' },
      { id: 'api2', label: 'Backend API 2', x: 650, y: 390, width: 180, kind: 'workload' },
      { id: 'private', label: 'Private Network\nbackends not exposed', x: 900, y: 335, width: 210, height: 72, kind: 'network' },
    ],
    edges: pt.proxy.edges,
  },
  identity: {
    ...pt.identity,
    title: 'Identity: authentication, tokens, policy, and resource access',
    description: 'Modern identity separates authentication from authorization. An IdP authenticates a user or workload; tokens and claims carry context; a Policy Enforcement Point applies policy before access reaches the resource. Zero Trust decisions rely on identity and context rather than network location alone.',
    nodes: [
      { id: 'principal', label: 'Principal\nUser / Workload', x: 25, y: 185, width: 190, height: 72, kind: 'client' },
      { id: 'idp', label: 'Identity Provider\nMFA · federation · workload identity', x: 275, y: 65, width: 250, height: 82, kind: 'security' },
      { id: 'token', label: 'Token / Credential\nissuer · subject · audience · scope', x: 275, y: 300, width: 250, height: 82, kind: 'data' },
      { id: 'pep', label: 'Policy Enforcement Point\nAPI Gateway / proxy / service', x: 615, y: 185, width: 250, height: 82, kind: 'security' },
      { id: 'pdp', label: 'Policy Decision Point\nRBAC / ABAC / context', x: 615, y: 350, width: 250, height: 82, kind: 'decision' },
      { id: 'resource', label: 'Protected Resource\nAPI · data · infrastructure', x: 930, y: 185, width: 210, height: 82, kind: 'workload' },
    ],
    edges: [
      { from: 'principal', to: 'idp', label: 'authenticate', animated: true }, { from: 'idp', to: 'token', label: 'issue short-lived credential' },
      { from: 'token', to: 'principal', label: 'credential' }, { from: 'principal', to: 'pep', label: 'request + credential', animated: true },
      { from: 'pep', to: 'pdp', label: 'identity + claims + context' }, { from: 'pdp', to: 'pep', label: 'allow / deny' },
      { from: 'pep', to: 'resource', label: 'authorized request', animated: true },
    ],
  },
};

export function getSecurityDepthDiagram(key: SecurityDiagramKey, locale: 'pt' | 'en') {
  return (locale === 'en' ? en : pt)[key];
}
