import type { WikiArticle } from './wiki';

export const wikiArticlesEn: WikiArticle[] = [
  {
    slug: 'kubernetes',
    title: 'Kubernetes',
    category: 'Containers and orchestration',
    summary: 'Container orchestration platform for running, scaling, and operating distributed applications.',
    aliases: ['K8s', 'container orchestration'],
    concepts: ['Pod', 'Deployment', 'Service', 'Ingress', 'Scheduler', 'etcd', 'RBAC', 'NetworkPolicy'],
    sections: [
      { id: 'fundamentos', title: 'Fundamentals', level: 'Fundamentos', summary: 'Kubernetes continuously reconciles declarative desired state and replaces failed workload components.', points: ['Pods are the smallest deployable units and can contain one or more containers.', 'Deployments manage ReplicaSets and progressive updates for stateless applications.', 'Services provide stable network identity for dynamic sets of Pods.', 'ConfigMaps and Secrets separate configuration from application code.'] },
      { id: 'operacao', title: 'Operations and networking', level: 'Intermediário', summary: 'Day-to-day operation includes scheduling, probes, resource management, storage, and network troubleshooting.', points: ['Requests influence scheduling while limits constrain CPU and memory consumption.', 'Readiness controls traffic eligibility while liveness can restart unhealthy containers.', 'Ingress exposes HTTP/HTTPS routes and requires an Ingress Controller.', 'Persistent volumes decouple data lifecycle from Pod lifecycle.'] },
      { id: 'arquitetura', title: 'Architecture and high availability', level: 'Avançado', summary: 'Resilient clusters depend on a redundant control plane, healthy etcd, and appropriate workload placement.', points: ['The API Server is the control-plane entry point; controllers reconcile desired state.', 'etcd requires quorum and low latency to preserve consistency and availability.', 'Affinity, anti-affinity, topology spread constraints, and taints influence placement.', 'PodDisruptionBudgets constrain voluntary disruption during maintenance.'] },
      { id: 'especialista', title: 'Security and deep troubleshooting', level: 'Especialista', summary: 'Operational maturity requires policy, observability, and systematic investigation of distributed failures.', points: ['RBAC should enforce least privilege and separate human identities from service accounts.', 'NetworkPolicies control east-west traffic when supported by the CNI.', 'Admission controllers and webhooks validate or mutate resources before persistence.', 'Troubleshooting should correlate events, logs, metrics, endpoints, DNS, CNI, and node state.'] },
    ],
    interviewQuestions: ['What is the difference between Deployment, StatefulSet, and DaemonSet?', 'What happens when a readiness probe fails?', 'How do you investigate a Service with no endpoints?', 'How does etcd quorum affect cluster availability?'],
    related: ['docker', 'helm', 'cicd', 'observabilidade', 'redes'],
  },
  {
    slug: 'docker',
    title: 'Docker and containers',
    category: 'Containers and orchestration',
    summary: 'Technology for packaging applications and dependencies into isolated and reproducible execution units.',
    aliases: ['containers', 'OCI'],
    concepts: ['Image', 'Container', 'Layer', 'Registry', 'Namespace', 'cgroup', 'Dockerfile'],
    sections: [
      { id: 'fundamentos', title: 'Images and containers', level: 'Fundamentos', summary: 'An image is an immutable artifact; a container is a running instance of that image.', points: ['Images consist of reusable layers and are identified by tags or digests.', 'Containers share the host kernel while namespaces provide isolation.', 'Registries store and distribute images.', 'Volumes preserve data outside the container writable layer.'] },
      { id: 'builds', title: 'Reproducible builds', level: 'Intermediário', summary: 'Small, deterministic, multi-stage Dockerfiles reduce image size and attack surface.', points: ['Order instructions to maximize cache reuse and avoid unnecessary rebuilds.', 'Use minimal base images and pinned versions when reproducibility matters.', 'Multi-stage builds keep compilers and development tooling out of the final image.', 'Run processes as a non-root user whenever possible.'] },
      { id: 'runtime', title: 'Runtime and isolation', level: 'Avançado', summary: 'The runtime combines namespaces, cgroups, capabilities, and layered filesystems.', points: ['cgroups account for and limit resources such as CPU and memory.', 'Linux capabilities remove privileges a process does not need.', 'Seccomp restricts syscalls while AppArmor or SELinux add policy controls.', 'OCI standards enable interoperability among container tooling and runtimes.'] },
      { id: 'especialista', title: 'Supply chain and performance', level: 'Especialista', summary: 'Mature operation includes signing, SBOMs, scanning, and build/pull optimization.', points: ['An SBOM records components included in an image.', 'Signatures and provenance verification reduce artifact tampering risk.', 'Digests remove ambiguity caused by mutable tags.', 'Smaller images reduce transfer time, pull latency, and vulnerability exposure.'] },
    ],
    interviewQuestions: ['What is the difference between an image and a container?', 'How does a multi-stage build work?', 'Why is a container not equivalent to a virtual machine?'],
    related: ['kubernetes', 'cicd', 'linux', 'seguranca'],
  },
  {
    slug: 'helm',
    title: 'Helm',
    category: 'Containers and orchestration',
    summary: 'Kubernetes package manager based on charts, templates, releases, and configurable values.',
    aliases: ['Helm Charts'],
    concepts: ['Chart', 'Release', 'Template', 'values.yaml', 'Repository', 'Hook'],
    sections: [
      { id: 'fundamentos', title: 'Charts and releases', level: 'Fundamentos', summary: 'A chart packages parameterized manifests while a release represents one installed instance.', points: ['Chart.yaml describes the package and dependencies.', 'values.yaml defines default values that can be overridden per environment.', 'Templates render Kubernetes manifests from values.', 'helm install, upgrade, and rollback manage the release lifecycle.'] },
      { id: 'templates', title: 'Safe templates', level: 'Intermediário', summary: 'Templates should remain readable, predictable, and validated before deployment.', points: ['Helpers reduce duplication of labels, names, and selectors.', 'helm template renders manifests for inspection before deployment.', 'helm lint detects common structural problems.', 'JSON schemas can validate values types and fields.'] },
      { id: 'dependencias', title: 'Dependencies and environments', level: 'Avançado', summary: 'Reusable charts need stable configuration contracts and minimal environment-specific overrides.', points: ['Subcharts encapsulate dependent components.', 'Environment values files should contain only necessary differences.', 'Library charts standardize shared templates.', 'Immutable resources and hooks require care during upgrades.'] },
      { id: 'especialista', title: 'Helm in GitOps', level: 'Especialista', summary: 'In GitOps, Git defines configuration and a reconciler continuously applies the chart.', points: ['Immutable image tags improve rollback and auditability.', 'Argo CD can render charts directly from Git repositories.', 'Secrets should not be stored as plaintext in values files.', 'Desired/live differences should be deliberate and documented.'] },
    ],
    interviewQuestions: ['What is the difference between a chart and a release?', 'How do you validate a chart before deployment?', 'How do you use Helm with Argo CD?'],
    related: ['kubernetes', 'cicd', 'terraform'],
  },
  {
    slug: 'aws',
    title: 'Amazon Web Services',
    category: 'Cloud',
    summary: 'Public cloud platform providing compute, networking, storage, data, messaging, and security services.',
    aliases: ['AWS', 'Amazon Cloud'],
    concepts: ['Region', 'Availability Zone', 'VPC', 'IAM', 'EC2', 'S3', 'RDS', 'EKS'],
    sections: [
      { id: 'fundamentos', title: 'Global model and core services', level: 'Fundamentos', summary: 'AWS organizes resources into Regions and Availability Zones under a shared-responsibility model.', points: ['Regions are independent geographic areas; Availability Zones isolate failures within a Region.', 'IAM controls identities, roles, policies, and API access.', 'EC2 provides virtual machines while S3 provides object storage.', 'Customers protect data, identities, and configuration under their responsibility.'] },
      { id: 'arquitetura', title: 'Resilient architectures', level: 'Intermediário', summary: 'Resilience combines multi-AZ redundancy, decoupling, and automated recovery.', points: ['Application Load Balancer distributes HTTP/HTTPS traffic among healthy targets.', 'Auto Scaling adjusts capacity from metrics and policies.', 'RDS Multi-AZ improves availability but does not replace backups.', 'SQS decouples producers and consumers and absorbs bursts.'] },
      { id: 'rede-seguranca', title: 'Networking and security', level: 'Avançado', summary: 'VPC design, routing, and identity controls must be designed together.', points: ['Public and private subnets are determined by routing, not by their names.', 'Security Groups are stateful while Network ACLs are stateless.', 'VPC Endpoints provide private access to supported AWS services.', 'KMS manages keys and integrates encryption with many AWS services.'] },
      { id: 'especialista', title: 'Governance and scale', level: 'Especialista', summary: 'Large environments use multiple accounts, landing zones, observability, and organizational policy.', points: ['AWS Organizations and SCPs establish governance boundaries across accounts.', 'Transit Gateway centralizes connectivity among VPCs and external networks.', 'The Well-Architected Framework guides security, reliability, performance, cost, and operations decisions.', 'FinOps connects architecture, consumption, and financial accountability.'] },
    ],
    interviewQuestions: ['What is the difference between a Security Group and a Network ACL?', 'How would you design a highly available application across two Availability Zones?', 'When would you use SQS instead of synchronous communication?'],
    related: ['terraform', 'redes', 'seguranca', 'kubernetes'],
  },
  {
    slug: 'azure',
    title: 'Microsoft Azure',
    category: 'Cloud',
    summary: 'Microsoft public cloud platform for compute, identity, networking, data, and managed services.',
    aliases: ['Azure', 'Microsoft Cloud'],
    concepts: ['Subscription', 'Resource Group', 'VNet', 'Entra ID', 'VM', 'Storage Account', 'AKS'],
    sections: [
      { id: 'fundamentos', title: 'Resource organization', level: 'Fundamentos', summary: 'Azure organizes resources by tenant, subscription, resource group, and Region.', points: ['Microsoft Entra ID manages identities and authentication.', 'Resource Groups group resources with related lifecycles.', 'Subscriptions define administrative, billing, and quota boundaries.', 'Azure Resource Manager provides the declarative management layer.'] },
      { id: 'servicos', title: 'Compute and data', level: 'Intermediário', summary: 'Azure offers VMs, application platforms, managed databases, and Kubernetes.', points: ['Virtual Machine Scale Sets automate scalable groups of VMs.', 'App Service hosts web applications without direct OS administration.', 'Azure SQL provides managed relational databases.', 'AKS provides managed Kubernetes integrated with the Azure ecosystem.'] },
      { id: 'rede-seguranca', title: 'Networking and security', level: 'Avançado', summary: 'VNets, NSGs, private endpoints, and identity controls define secure connectivity.', points: ['VNets and subnets establish network boundaries.', 'NSGs filter traffic using stateful rules.', 'Private Endpoints expose supported services through private IPs.', 'Managed Identities reduce the need for long-lived application credentials.'] },
      { id: 'especialista', title: 'Governance at scale', level: 'Especialista', summary: 'Enterprise Azure environments combine management groups, policy, landing zones, and centralized observability.', points: ['Management Groups organize subscriptions hierarchically.', 'Azure Policy enforces or audits configuration at scale.', 'Landing Zones standardize identity, networking, governance, and operations.', 'Hub-and-spoke topologies centralize shared network services.'] },
    ],
    interviewQuestions: ['What is the difference between a VNet and a subnet?', 'When should you use a Managed Identity?', 'How would you design private access to a PaaS service?'],
    related: ['terraform', 'redes', 'seguranca', 'kubernetes'],
  },
  {
    slug: 'gcp',
    title: 'Google Cloud Platform',
    category: 'Cloud',
    summary: 'Google public cloud platform for compute, networking, storage, data, analytics, and Kubernetes.',
    aliases: ['GCP', 'Google Cloud'],
    concepts: ['Project', 'VPC', 'IAM', 'Compute Engine', 'Cloud Storage', 'GKE', 'Pub/Sub'],
    sections: [
      { id: 'fundamentos', title: 'Projects and global infrastructure', level: 'Fundamentos', summary: 'GCP organizes resources into organizations, folders, and projects, with globally scoped VPC networking.', points: ['Projects provide a primary boundary for APIs, billing, quotas, and IAM.', 'Regions contain zones used to distribute workloads.', 'IAM policies bind principals to roles on resources.', 'Compute Engine provides VMs and Cloud Storage provides object storage.'] },
      { id: 'servicos', title: 'Managed services', level: 'Intermediário', summary: 'Managed services reduce infrastructure work while preserving cloud-native scaling patterns.', points: ['GKE provides managed Kubernetes.', 'Cloud Run executes containerized services without managing servers.', 'Cloud SQL provides managed relational databases.', 'Pub/Sub provides scalable asynchronous messaging.'] },
      { id: 'rede-seguranca', title: 'Networking and identity', level: 'Avançado', summary: 'VPC design, firewall policy, service identities, and private connectivity shape secure architecture.', points: ['VPC networks are global while subnets are regional.', 'Firewall rules control ingress and egress to resources.', 'Private Service Connect enables private service consumption.', 'Service accounts provide workload identities.'] },
      { id: 'especialista', title: 'Security and organization at scale', level: 'Especialista', summary: 'Organization policy, workload identity, and service perimeters reduce exposure in large environments.', points: ['Organization Policies restrict configurations across the resource hierarchy.', 'Workload Identity avoids static keys for applications.', 'VPC Service Controls can create service perimeters around supported APIs.', 'Centralized logging and audit data support detection and incident response.'] },
    ],
    interviewQuestions: ['What is the difference between a project and a VPC?', 'Why use a service account instead of a user credential for workloads?', 'When would you use Pub/Sub?'],
    related: ['terraform', 'redes', 'seguranca', 'kubernetes'],
  },
  {
    slug: 'terraform',
    title: 'Terraform',
    category: 'Automation and IaC',
    summary: 'Declarative Infrastructure as Code tool that plans and applies changes through provider APIs.',
    aliases: ['HashiCorp Terraform', 'IaC'],
    concepts: ['Provider', 'Resource', 'Data Source', 'State', 'Module', 'Plan', 'Backend', 'Workspace'],
    sections: [
      { id: 'fundamentos', title: 'Configuration and providers', level: 'Fundamentos', summary: 'Terraform describes desired infrastructure with HCL and uses providers to interact with external APIs.', points: ['Resources declare infrastructure Terraform should manage.', 'Data sources read external information without owning the resource lifecycle.', 'Variables parameterize configurations and outputs expose useful values.', 'terraform plan previews proposed actions before apply.'] },
      { id: 'state-modulos', title: 'Remote state and modules', level: 'Intermediário', summary: 'Teams need protected remote state, locking, and modules with clear interfaces.', points: ['Remote backends centralize state and can support locking.', 'State may contain sensitive metadata and must be protected and encrypted.', 'Modules encapsulate reusable patterns through variables and outputs.', 'Provider and module versions should be deliberately constrained.'] },
      { id: 'ciclo', title: 'Lifecycle and refactoring', level: 'Avançado', summary: 'Safe changes require understanding dependencies, graph behavior, and state operations.', points: ['Terraform infers dependencies from references and supports depends_on when required.', 'moved blocks preserve resource identity during refactoring.', 'Import associates existing infrastructure with Terraform configuration.', 'create_before_destroy and prevent_destroy modify lifecycle behavior.'] },
      { id: 'especialista', title: 'Governance and automation at scale', level: 'Especialista', summary: 'Mature pipelines separate validation, planning, approval, apply, and policy enforcement.', points: ['Plans should be tied to the reviewed commit to prevent unexpected changes.', 'Policy as Code applies constraints before provisioning.', 'Multi-environment structures should minimize duplication and coupling.', 'Drift should be detected, investigated, and reconciled through the declarative workflow.'] },
    ],
    interviewQuestions: ['Why does Terraform need state?', 'How do you prevent concurrent operations against the same state?', 'What is the difference between a module, resource, and data source?'],
    related: ['aws', 'azure', 'gcp', 'cicd', 'ansible'],
  },
  {
    slug: 'ansible',
    title: 'Ansible',
    category: 'Automation and IaC',
    summary: 'Agentless automation tool for configuration management, orchestration, and remote execution.',
    aliases: ['Configuration Management'],
    concepts: ['Inventory', 'Playbook', 'Task', 'Module', 'Role', 'Handler', 'Fact'],
    sections: [
      { id: 'fundamentos', title: 'Inventory and playbooks', level: 'Fundamentos', summary: 'Ansible usually connects over SSH and executes modules described in YAML playbooks.', points: ['Inventories group hosts and variables.', 'Playbooks associate hosts with ordered task lists.', 'Modules perform idempotent operations whenever possible.', 'Facts expose information collected from managed systems.'] },
      { id: 'roles', title: 'Roles and reuse', level: 'Intermediário', summary: 'Roles organize tasks, handlers, templates, files, and defaults into reusable components.', points: ['Handlers run actions triggered by notified changes.', 'Jinja2 templates generate files from variables.', 'group_vars and host_vars separate configuration by scope.', 'Tags allow controlled execution of playbook subsets.'] },
      { id: 'seguranca', title: 'Secrets and controlled execution', level: 'Avançado', summary: 'Safe automation requires credential protection, validation, and limiting change impact.', points: ['Ansible Vault protects values at rest, but encryption keys still require proper management.', 'Check mode previews changes when supported by the module.', 'serial and strategy settings control how many hosts change at once.', 'become should be used only for tasks requiring elevated privilege.'] },
      { id: 'especialista', title: 'Automation at scale', level: 'Especialista', summary: 'Large-scale execution depends on dynamic inventory, observability, and role testing.', points: ['Dynamic inventories query cloud platforms and CMDBs.', 'Execution environments standardize collections and dependencies.', 'Molecule can test roles in disposable environments.', 'Automation should produce auditable logs and deterministic results.'] },
    ],
    interviewQuestions: ['What does idempotency mean in Ansible?', 'What is the difference between a task, handler, and role?', 'When should you use Terraform and when should you use Ansible?'],
    related: ['terraform', 'linux', 'cicd'],
  },
  {
    slug: 'cicd',
    title: 'CI/CD and GitOps',
    category: 'Automation and IaC',
    summary: 'Practices for validating, packaging, publishing, and deploying software changes with traceability.',
    aliases: ['Continuous Integration', 'Continuous Delivery', 'GitOps'],
    concepts: ['Pipeline', 'Artifact', 'Runner', 'Deployment', 'Rollback', 'Argo CD', 'GitHub Actions'],
    sections: [
      { id: 'fundamentos', title: 'Continuous Integration', level: 'Fundamentos', summary: 'CI validates every change through builds, tests, and automated analysis.', points: ['Pipelines should fail fast on lint, type, or test failures.', 'Artifacts should be built once and promoted between environments.', 'Pipeline secrets must not appear in logs.', 'Pull requests establish review before integration.'] },
      { id: 'entrega', title: 'Delivery and deployment', level: 'Intermediário', summary: 'CD automates publication and deployment with approval and rollback criteria.', points: ['Immutable tags associate an image with a specific commit.', 'Rolling updates reduce downtime during releases.', 'Health checks prevent promotion of unhealthy instances.', 'Environments should differ by configuration rather than rebuilt artifacts.'] },
      { id: 'gitops', title: 'GitOps', level: 'Avançado', summary: 'In GitOps, Git stores desired state and a reconciler continuously applies changes to the environment.', points: ['Argo CD compares desired manifests with live cluster resources.', 'Self-heal corrects unauthorized drift.', 'Prune removes resources no longer present in desired state.', 'Git history provides auditability and supports declarative rollback.'] },
      { id: 'especialista', title: 'Supply-chain security', level: 'Especialista', summary: 'Mature pipelines verify artifact origin, contents, and promotion policy.', points: ['SBOMs document dependencies contained in artifacts.', 'Signing and provenance show how and where an artifact was built.', 'OIDC reduces the need for long-lived cloud credentials.', 'Admission policies can block unapproved images.'] },
    ],
    interviewQuestions: ['What is the difference between continuous delivery and continuous deployment?', 'How does Argo CD detect and correct drift?', 'Why use immutable image tags?'],
    related: ['kubernetes', 'helm', 'docker', 'terraform'],
  },
  {
    slug: 'linux',
    title: 'Linux',
    category: 'Operating systems',
    summary: 'Operating system and ecosystem central to servers, containers, cloud platforms, and DevOps.',
    aliases: ['GNU/Linux', 'Unix-like'],
    concepts: ['Process', 'Filesystem', 'systemd', 'Permission', 'Socket', 'Namespace', 'cgroup'],
    sections: [
      { id: 'fundamentos', title: 'Filesystem, users, and processes', level: 'Fundamentos', summary: 'Linux represents many resources as files and organizes execution through processes and permissions.', points: ['Traditional permissions use owner, group, and read/write/execute bits.', 'Processes have a PID, state, priority, and file descriptors.', 'Directories such as /etc, /var, /proc, and /sys serve distinct purposes.', 'systemd manages services, targets, timers, and journal logs.'] },
      { id: 'recursos', title: 'CPU, memory, and storage', level: 'Intermediário', summary: 'Diagnosis requires distinguishing actual resource use, recoverable cache, and system limits.', points: ['Load average measures runnable or blocked tasks, not only CPU utilization.', 'Available memory accounts for cache that the kernel can reclaim.', 'Inodes store file metadata and can be exhausted before byte capacity.', 'File-descriptor limits constrain open files, sockets, and pipes.'] },
      { id: 'rede-kernel', title: 'Networking and kernel', level: 'Avançado', summary: 'Network tools and kernel interfaces reveal connection paths and bottlenecks.', points: ['ip replaces legacy tools for addresses, routes, and interfaces.', 'ss inspects sockets and TCP states.', 'sysctl changes kernel parameters at runtime.', 'Namespaces and cgroups form the isolation foundation of containers.'] },
      { id: 'especialista', title: 'Observability and performance analysis', level: 'Especialista', summary: 'Deep analysis correlates scheduler behavior, I/O, memory, networking, syscalls, and application behavior.', points: ['strace traces syscalls and signals for a process.', 'perf analyzes CPU events and hotspots.', 'eBPF enables programmable instrumentation with relatively low overhead.', 'Diagnosis should validate hypotheses with metrics before changing tunables.'] },
    ],
    interviewQuestions: ['What is an inode and how can it make a filesystem appear full?', 'What is the difference between a process and a thread?', 'How do you investigate high load with apparently low CPU usage?'],
    related: ['redes', 'docker', 'observabilidade', 'seguranca'],
  },
  {
    slug: 'vmware',
    title: 'VMware and virtualization',
    category: 'Operating systems',
    summary: 'Infrastructure virtualization based on hypervisors, virtual machines, software-defined networking, and storage.',
    aliases: ['vSphere', 'ESXi', 'virtualization'],
    concepts: ['Hypervisor', 'VM', 'ESXi', 'vCenter', 'vMotion', 'Datastore', 'vSwitch'],
    sections: [
      { id: 'fundamentos', title: 'Hypervisors and virtual machines', level: 'Fundamentos', summary: 'A hypervisor shares physical hardware among isolated operating systems.', points: ['ESXi is the bare-metal hypervisor in the vSphere platform.', 'vCenter centralizes management of hosts and VMs.', 'Datastores store virtual-machine disks and files.', 'Snapshots capture state for temporary operations but do not replace backups.'] },
      { id: 'cluster', title: 'Clusters and mobility', level: 'Intermediário', summary: 'Clusters combine hosts for availability, load balancing, and maintenance.', points: ['vMotion moves running VMs between compatible hosts.', 'Storage vMotion moves virtual disks between datastores.', 'HA restarts VMs after host failure.', 'DRS recommends or performs workload redistribution.'] },
      { id: 'rede-storage', title: 'Networking and storage', level: 'Avançado', summary: 'Performance depends on correct design of uplinks, port groups, multipathing, and storage capacity.', points: ['vSwitches connect virtual interfaces to physical uplinks.', 'VLANs segment traffic through port groups.', 'Multipathing improves storage access resilience.', 'Overcommit must account for peaks and real resource contention.'] },
      { id: 'especialista', title: 'Capacity and troubleshooting', level: 'Especialista', summary: 'Advanced investigation distinguishes VM consumption, host contention, and infrastructure latency.', points: ['CPU Ready measures time waiting to be scheduled by the hypervisor.', 'Ballooning and swapping indicate memory pressure at different layers.', 'Storage latency should be decomposed across guest, kernel, and device layers.', 'Changes must account for hardware compatibility, versions, and cluster dependencies.'] },
    ],
    interviewQuestions: ['What is the difference between HA, DRS, and vMotion?', 'Why does a snapshot not replace a backup?', 'What does CPU Ready indicate?'],
    related: ['linux', 'redes', 'observabilidade'],
  },
  {
    slug: 'redes',
    title: 'Computer networking',
    category: 'Networking and security',
    summary: 'Communication principles covering addressing, routing, transport, DNS, HTTP, NAT, and network troubleshooting.',
    aliases: ['Networking', 'TCP/IP'],
    concepts: ['Ethernet', 'ARP', 'IP', 'Routing', 'TCP', 'UDP', 'DNS', 'HTTP', 'NAT'],
    sections: [
      { id: 'fundamentos', title: 'Layers and addressing', level: 'Fundamentos', summary: 'Network communication combines encapsulation, local addressing, IP addressing, and routing.', points: ['Ethernet delivers frames within a local broadcast domain.', 'ARP resolves IPv4 addresses to MAC addresses on the local network.', 'IP identifies source and destination across networks.', 'The routing table determines the next hop for each destination.'] },
      { id: 'transporte', title: 'TCP, UDP, DNS, and HTTP', level: 'Intermediário', summary: 'Transport and application protocols provide different delivery guarantees and communication models.', points: ['TCP provides reliable, ordered, connection-oriented byte streams.', 'UDP reduces transport overhead and leaves reliability to the application when needed.', 'DNS maps names to records such as A, AAAA, CNAME, and MX.', 'HTTP defines requests, responses, methods, headers, and status codes.'] },
      { id: 'infraestrutura', title: 'Routing, NAT, and load balancing', level: 'Avançado', summary: 'Modern networks combine routing, address translation, firewalls, and proxies across multiple layers.', points: ['NAT changes addresses or ports while forwarding traffic.', 'Layer 4 load balancers operate on connections while Layer 7 load balancers understand application protocols.', 'Route symmetry matters when stateful devices inspect connections.', 'VPNs and private links extend routing domains between separate networks.'] },
      { id: 'especialista', title: 'Deep troubleshooting', level: 'Especialista', summary: 'Expert troubleshooting follows the packet path and validates assumptions at each layer.', points: ['Capture traffic near source and destination to determine where packets disappear.', 'Validate routes, ARP/neighbor state, firewall policy, MTU, and return paths.', 'Distinguish DNS, TCP handshake, TLS, and application failures instead of treating them as one symptom.', 'Use flow logs and packet captures as evidence before changing network configuration.'] },
    ],
    interviewQuestions: ['What is the difference between TCP and UDP?', 'How do you troubleshoot intermittent packet loss?', 'How does NAT affect end-to-end communication?'],
    related: ['seguranca', 'linux', 'kubernetes', 'sistemas-distribuidos'],
  },
  {
    slug: 'seguranca',
    title: 'Security and protocols',
    category: 'Networking and security',
    summary: 'Principles and protocols for protecting identity, communications, data, workloads, and infrastructure.',
    aliases: ['Cybersecurity', 'TLS', 'OAuth 2.0', 'Zero Trust'],
    concepts: ['CIA', 'TLS', 'PKI', 'OAuth 2.0', 'OIDC', 'RBAC', 'Encryption', 'Zero Trust'],
    sections: [
      { id: 'fundamentos', title: 'Security fundamentals', level: 'Fundamentos', summary: 'Confidentiality, integrity, and availability guide technical and operational controls.', points: ['Authentication verifies identity while authorization determines permitted actions.', 'Encryption in transit and at rest protects data in different contexts.', 'Least privilege limits access to what is required for a task.', 'Defense in depth combines independent preventive, detective, and recovery controls.'] },
      { id: 'protocolos', title: 'TLS, certificates, and identity', level: 'Intermediário', summary: 'TLS uses cryptography and certificates to authenticate endpoints and protect communication channels.', points: ['PKI connects certificates, certificate authorities, and chains of trust.', 'TLS negotiates parameters and establishes session keys.', 'OAuth 2.0 delegates authorization while OpenID Connect adds identity.', 'Tokens should have the smallest practical scope and lifetime.'] },
      { id: 'arquitetura', title: 'Secure architecture', level: 'Avançado', summary: 'Security should be embedded across identity, networking, workloads, data, and the software supply chain.', points: ['Segmentation limits lateral movement.', 'Secret managers keep credentials out of source code and images.', 'A WAF blocks known HTTP attack patterns but does not replace application fixes.', 'Audit logs should be centralized and protected from alteration.'] },
      { id: 'especialista', title: 'Threat modeling and response', level: 'Especialista', summary: 'Maturity requires threat modeling, risk prioritization, and evidence-based response.', points: ['Threat modeling identifies assets, trust boundaries, threats, and mitigations.', 'Zero Trust requires continuous verification, contextual decisions, and least privilege.', 'Incident response preserves evidence and avoids impulsive containment actions.', 'Controls should be evaluated by measured effectiveness, not documentation alone.'] },
    ],
    interviewQuestions: ['What is the difference between OAuth 2.0 and OpenID Connect?', 'How does a certificate chain of trust work?', 'What does Zero Trust mean in practice?'],
    related: ['redes', 'linux', 'kubernetes', 'cicd'],
  },
  {
    slug: 'kafka',
    title: 'Apache Kafka',
    category: 'Data and messaging',
    summary: 'Distributed event-streaming platform based on durable ordered logs, partitions, producers, and consumer groups.',
    aliases: ['Kafka', 'Event Streaming'],
    concepts: ['Topic', 'Partition', 'Broker', 'Producer', 'Consumer', 'Consumer Group', 'Offset', 'ISR'],
    sections: [
      { id: 'fundamentos', title: 'Topics, partitions, and offsets', level: 'Fundamentos', summary: 'Kafka stores records in ordered partition logs and addresses positions with offsets.', points: ['Topics organize event streams.', 'Partitions provide parallelism and ordering within each partition.', 'Producers append records while consumers read them.', 'Offsets represent a consumer position in a partition.'] },
      { id: 'consumo', title: 'Consumer groups and delivery', level: 'Intermediário', summary: 'Consumer groups distribute partitions among consumers and enable horizontal processing.', points: ['Within one group, a partition is assigned to one consumer at a time.', 'Rebalances redistribute partitions when group membership changes.', 'Offset commit strategy affects duplicate processing and recovery behavior.', 'At-least-once processing is common and requires idempotent consumers.'] },
      { id: 'cluster', title: 'Replication and resilience', level: 'Avançado', summary: 'Replication protects partitions against broker loss and requires careful durability settings.', points: ['Partition replicas are distributed across brokers.', 'An in-sync replica tracks the leader closely enough to remain eligible.', 'Replication factor and min.insync.replicas affect failure tolerance.', 'Producer acknowledgements trade latency against durability guarantees.'] },
      { id: 'especialista', title: 'Performance and failure modes', level: 'Especialista', summary: 'Advanced operation balances throughput, ordering, lag, storage, and recovery characteristics.', points: ['Partition count influences parallelism and operational overhead.', 'Consumer lag measures how far processing is behind produced data.', 'Hot partitions can create uneven broker load.', 'Capacity planning must account for retention, replication, ingress, egress, and recovery traffic.'] },
    ],
    interviewQuestions: ['How does a consumer group work?', 'What determines ordering in Kafka?', 'How does min.insync.replicas affect durability?'],
    related: ['sistemas-distribuidos', 'redis', 'observabilidade'],
  },
  {
    slug: 'redis',
    title: 'Redis',
    category: 'Data and messaging',
    summary: 'In-memory data store commonly used for caching, sessions, counters, queues, and low-latency state.',
    aliases: ['Redis OSS', 'In-memory store'],
    concepts: ['Key', 'TTL', 'Cache', 'Eviction', 'Replication', 'Sentinel', 'Cluster', 'Persistence'],
    sections: [
      { id: 'fundamentos', title: 'Data structures and TTL', level: 'Fundamentos', summary: 'Redis stores keys with data structures optimized for fast in-memory access.', points: ['Strings, hashes, lists, sets, and sorted sets support different access patterns.', 'TTL expires data automatically.', 'Atomic commands simplify counters and coordination patterns.', 'Memory is the primary working set, so capacity must be controlled.'] },
      { id: 'cache', title: 'Caching patterns', level: 'Intermediário', summary: 'Caching improves latency but introduces freshness, invalidation, and failure considerations.', points: ['Cache-aside loads missing values from the source of truth.', 'TTL limits stale data lifetime.', 'Eviction policies determine what happens when maxmemory is reached.', 'Cache stampedes require coordination, jitter, or request coalescing.'] },
      { id: 'ha', title: 'High availability and persistence', level: 'Avançado', summary: 'Replication, Sentinel, clustering, and persistence address different availability and durability needs.', points: ['Replication copies data to replicas for read scaling and failover support.', 'Sentinel coordinates failover for non-clustered deployments.', 'Redis Cluster shards keys across nodes.', 'RDB and AOF provide different persistence characteristics.'] },
      { id: 'especialista', title: 'Operational failure modes', level: 'Especialista', summary: 'Advanced operation requires controlling memory, latency, failover, and key-distribution behavior.', points: ['Large keys and expensive commands can block the event loop.', 'Uneven key distribution can create hot shards.', 'Failover can expose replication lag and consistency tradeoffs.', 'Monitor memory fragmentation, command latency, evictions, and replication health.'] },
    ],
    interviewQuestions: ['When should Redis be used as a cache rather than a database?', 'What is the difference between Sentinel and Redis Cluster?', 'How do eviction policies affect application behavior?'],
    related: ['kafka', 'sistemas-distribuidos', 'observabilidade'],
  },
  {
    slug: 'sistemas-distribuidos',
    title: 'Distributed systems',
    category: 'Architecture',
    summary: 'Systems in which independent nodes coordinate over unreliable networks to provide a coherent service.',
    aliases: ['Distributed Computing', 'Distributed Architecture'],
    concepts: ['Consistency', 'Availability', 'Partition', 'Quorum', 'Consensus', 'Replication', 'Idempotency'],
    sections: [
      { id: 'fundamentos', title: 'Failure and communication', level: 'Fundamentos', summary: 'Distributed systems must assume partial failure, variable latency, and message loss or duplication.', points: ['A remote call can fail independently of the caller.', 'Timeouts are required because waiting forever is not a recovery strategy.', 'Retries can duplicate operations unless requests are idempotent.', 'Observability must preserve correlation across service boundaries.'] },
      { id: 'consistencia', title: 'Consistency and replication', level: 'Intermediário', summary: 'Replication improves resilience but introduces choices about ordering, freshness, and coordination.', points: ['Strong consistency typically requires more coordination.', 'Eventual consistency allows replicas to converge over time.', 'Quorum reads and writes use overlapping majorities to constrain stale results.', 'Conflict resolution depends on the data model and application semantics.'] },
      { id: 'consenso', title: 'Consensus and leader election', level: 'Avançado', summary: 'Consensus algorithms allow nodes to agree on ordered state despite failures.', points: ['Leader-based protocols simplify ordered replication.', 'A majority quorum prevents two independent majorities in the same membership configuration.', 'Network partitions may leave a minority unable to make progress.', 'Membership changes must preserve quorum safety.'] },
      { id: 'especialista', title: 'Resilience patterns', level: 'Especialista', summary: 'Mature designs combine idempotency, backpressure, circuit breaking, queues, and graceful degradation.', points: ['Backpressure prevents fast producers from overwhelming slower consumers.', 'Circuit breakers reduce repeated load against failing dependencies.', 'Bulkheads isolate failures between resource pools.', 'Recovery objectives should be validated through realistic failure testing.'] },
    ],
    interviewQuestions: ['What does CAP theorem actually imply?', 'Why are retries dangerous without idempotency?', 'How does quorum protect a replicated system?'],
    related: ['kafka', 'redis', 'kubernetes', 'observabilidade'],
  },
  {
    slug: 'observabilidade',
    title: 'Observability',
    category: 'Operations and reliability',
    summary: 'Practices for understanding system behavior through metrics, logs, traces, events, and contextual telemetry.',
    aliases: ['Monitoring', 'Telemetry', 'SRE Observability'],
    concepts: ['Metrics', 'Logs', 'Traces', 'SLI', 'SLO', 'Alerting', 'OpenTelemetry'],
    sections: [
      { id: 'fundamentos', title: 'Signals and telemetry', level: 'Fundamentos', summary: 'Metrics, logs, traces, and events answer different questions about system behavior.', points: ['Metrics efficiently represent numeric behavior over time.', 'Logs provide discrete contextual records.', 'Distributed traces correlate requests across services.', 'Consistent metadata makes signals easier to join during incidents.'] },
      { id: 'slo', title: 'SLIs, SLOs, and alerting', level: 'Intermediário', summary: 'Service objectives convert user-facing reliability expectations into measurable indicators.', points: ['SLIs measure behavior such as availability, latency, or correctness.', 'SLOs define target levels over a time window.', 'Error budgets connect reliability targets to delivery decisions.', 'Alerts should indicate actionable risk rather than every anomaly.'] },
      { id: 'troubleshooting', title: 'Correlation and troubleshooting', level: 'Avançado', summary: 'Effective investigation correlates multiple signals around a hypothesis and timeline.', points: ['Start from user impact and identify the affected dependency path.', 'Compare changes, saturation, errors, and latency around the incident window.', 'Trace IDs and structured fields improve cross-service correlation.', 'Dashboards should support investigation rather than only status display.'] },
      { id: 'especialista', title: 'Observability at scale', level: 'Especialista', summary: 'Large platforms must control telemetry cost, cardinality, retention, and signal quality.', points: ['High-cardinality labels can dramatically increase metric cost.', 'Sampling strategies trade trace volume against diagnostic detail.', 'Telemetry pipelines need buffering and backpressure.', 'Reliability of the observability stack itself must be monitored and tested.'] },
    ],
    interviewQuestions: ['What is the difference between monitoring and observability?', 'How do you define a useful SLO?', 'How do you investigate latency across multiple services?'],
    related: ['linux', 'kubernetes', 'sistemas-distribuidos', 'cicd'],
  },
];

export const wikiArticleBySlugEn = Object.fromEntries(wikiArticlesEn.map((article) => [article.slug, article]));
export const wikiCategoriesEn = [...new Set(wikiArticlesEn.map((article) => article.category))];
