export type KnowledgeLevel = "Fundamentos" | "Intermediário" | "Avançado" | "Especialista";

export type WikiSection = {
  id: string;
  title: string;
  level: KnowledgeLevel;
  summary: string;
  points: string[];
};

export type WikiArticle = {
  slug: string;
  title: string;
  category: string;
  summary: string;
  aliases: string[];
  concepts: string[];
  sections: WikiSection[];
  interviewQuestions: string[];
  related: string[];
};

export const wikiArticles: WikiArticle[] = [
  {
    slug: "kubernetes",
    title: "Kubernetes",
    category: "Containers e orquestração",
    summary: "Plataforma de orquestração para executar, escalar e operar aplicações distribuídas em containers.",
    aliases: ["K8s", "orquestração de containers"],
    concepts: ["Pod", "Deployment", "Service", "Ingress", "Scheduler", "etcd", "RBAC", "NetworkPolicy"],
    sections: [
      {
        id: "fundamentos",
        title: "Fundamentos",
        level: "Fundamentos",
        summary: "O Kubernetes mantém o estado desejado de workloads declarativos e substitui componentes que falham.",
        points: [
          "Pods são a menor unidade de execução e podem conter um ou mais containers.",
          "Deployments administram ReplicaSets e atualizações progressivas de aplicações stateless.",
          "Services oferecem identidade de rede estável para conjuntos dinâmicos de Pods.",
          "ConfigMaps e Secrets separam configuração do código da aplicação.",
        ],
      },
      {
        id: "operacao",
        title: "Operação e rede",
        level: "Intermediário",
        summary: "A operação diária envolve scheduling, probes, recursos, armazenamento e diagnóstico de rede.",
        points: [
          "Requests influenciam o scheduling; limits restringem CPU e memória consumidas.",
          "Readiness controla entrada de tráfego, enquanto liveness pode reiniciar containers defeituosos.",
          "Ingress publica rotas HTTP/HTTPS e depende de um Ingress Controller.",
          "Volumes persistentes desacoplam o ciclo de vida dos dados do ciclo de vida dos Pods.",
        ],
      },
      {
        id: "arquitetura",
        title: "Arquitetura e alta disponibilidade",
        level: "Avançado",
        summary: "Clusters resilientes dependem de control plane redundante, etcd saudável e distribuição correta dos workloads.",
        points: [
          "O API Server é a porta de entrada do control plane; controllers reconciliam o estado desejado.",
          "O etcd exige quorum e baixa latência para preservar consistência e disponibilidade.",
          "Affinity, anti-affinity, topology spread constraints e taints controlam posicionamento.",
          "PodDisruptionBudgets limitam interrupções voluntárias durante manutenção.",
        ],
      },
      {
        id: "especialista",
        title: "Segurança e troubleshooting profundo",
        level: "Especialista",
        summary: "A maturidade operacional exige políticas, observabilidade e investigação sistemática de falhas distribuídas.",
        points: [
          "RBAC deve aplicar privilégio mínimo e separar identidades humanas de service accounts.",
          "NetworkPolicies controlam tráfego leste-oeste quando o CNI oferece suporte.",
          "Admission Controllers e webhooks validam ou modificam recursos antes da persistência.",
          "Troubleshooting deve correlacionar eventos, logs, métricas, endpoints, DNS, CNI e estado do node.",
        ],
      },
    ],
    interviewQuestions: [
      "Qual é a diferença entre Deployment, StatefulSet e DaemonSet?",
      "O que acontece quando uma readiness probe falha?",
      "Como investigar um Service sem endpoints?",
      "Como o quorum do etcd afeta a disponibilidade do cluster?",
    ],
    related: ["docker", "helm", "cicd", "observabilidade", "redes"],
  },
  {
    slug: "docker",
    title: "Docker e containers",
    category: "Containers e orquestração",
    summary: "Tecnologia para empacotar aplicações e dependências em unidades isoladas e reproduzíveis.",
    aliases: ["containers", "OCI"],
    concepts: ["Image", "Container", "Layer", "Registry", "Namespace", "cgroup", "Dockerfile"],
    sections: [
      {
        id: "fundamentos",
        title: "Imagens e containers",
        level: "Fundamentos",
        summary: "Uma imagem é um artefato imutável; um container é uma instância executável dessa imagem.",
        points: [
          "Imagens são compostas por camadas reutilizáveis e identificadas por tags ou digests.",
          "Containers compartilham o kernel do host, mas usam namespaces para isolamento.",
          "Registries armazenam e distribuem imagens.",
          "Volumes preservam dados fora da camada gravável do container.",
        ],
      },
      {
        id: "builds",
        title: "Builds reproduzíveis",
        level: "Intermediário",
        summary: "Dockerfiles pequenos, determinísticos e multi-stage reduzem tamanho e superfície de ataque.",
        points: [
          "Ordene instruções para maximizar cache e evitar rebuilds desnecessários.",
          "Use imagens base mínimas e versões fixas quando a reprodutibilidade for importante.",
          "Multi-stage builds separam ferramentas de compilação da imagem final.",
          "Execute processos como usuário não-root sempre que possível.",
        ],
      },
      {
        id: "runtime",
        title: "Runtime e isolamento",
        level: "Avançado",
        summary: "O runtime combina namespaces, cgroups, capabilities e filesystem em camadas.",
        points: [
          "cgroups limitam e contabilizam recursos como CPU e memória.",
          "Linux capabilities permitem remover privilégios que um processo não precisa.",
          "Seccomp restringe syscalls e AppArmor ou SELinux aplicam políticas adicionais.",
          "O padrão OCI permite interoperabilidade entre ferramentas e runtimes.",
        ],
      },
      {
        id: "especialista",
        title: "Supply chain e desempenho",
        level: "Especialista",
        summary: "Operação madura inclui assinatura, SBOM, scanning e otimização do caminho de build e pull.",
        points: [
          "SBOM documenta componentes presentes na imagem.",
          "Assinaturas e verificação de proveniência reduzem risco de artefatos adulterados.",
          "Digests evitam ambiguidades associadas a tags mutáveis.",
          "Imagens menores reduzem tráfego, tempo de pull e exposição a vulnerabilidades.",
        ],
      },
    ],
    interviewQuestions: [
      "Qual é a diferença entre imagem e container?",
      "Como funciona um multi-stage build?",
      "Por que um container não é equivalente a uma máquina virtual?",
    ],
    related: ["kubernetes", "cicd", "linux", "seguranca"],
  },
  {
    slug: "helm",
    title: "Helm",
    category: "Containers e orquestração",
    summary: "Gerenciador de pacotes para Kubernetes baseado em charts, templates e valores configuráveis.",
    aliases: ["Helm Charts"],
    concepts: ["Chart", "Release", "Template", "values.yaml", "Repository", "Hook"],
    sections: [
      {
        id: "fundamentos",
        title: "Charts e releases",
        level: "Fundamentos",
        summary: "Um chart agrupa manifests parametrizados; uma release representa sua instalação em um cluster.",
        points: [
          "Chart.yaml descreve o pacote e suas dependências.",
          "values.yaml contém valores padrão substituíveis por ambiente.",
          "Templates geram manifests Kubernetes a partir dos valores.",
          "helm install, upgrade e rollback controlam o ciclo de vida da release.",
        ],
      },
      {
        id: "templates",
        title: "Templates seguros",
        level: "Intermediário",
        summary: "Templates devem permanecer legíveis, previsíveis e validados antes do deploy.",
        points: [
          "Helpers evitam repetição de labels, nomes e selectors.",
          "helm template permite inspecionar os manifests renderizados.",
          "helm lint detecta erros estruturais comuns.",
          "Schemas JSON podem validar tipos e campos de values.",
        ],
      },
      {
        id: "dependencias",
        title: "Dependências e ambientes",
        level: "Avançado",
        summary: "Charts reutilizáveis precisam de contratos de configuração estáveis e sobreposições mínimas.",
        points: [
          "Subcharts encapsulam componentes dependentes.",
          "Arquivos values por ambiente devem conter apenas diferenças necessárias.",
          "Bibliotecas de charts padronizam templates compartilhados.",
          "Recursos imutáveis e hooks exigem cuidado durante upgrades.",
        ],
      },
      {
        id: "especialista",
        title: "Helm em GitOps",
        level: "Especialista",
        summary: "Em GitOps, o Git define a configuração e o reconciliador aplica o chart de forma contínua.",
        points: [
          "Tags imutáveis de imagem tornam rollbacks e auditoria mais confiáveis.",
          "Argo CD pode renderizar charts diretamente a partir do repositório Git.",
          "Segredos não devem ser armazenados em texto simples nos values.",
          "Diferenças entre estado desejado e estado vivo devem ser deliberadas e documentadas.",
        ],
      },
    ],
    interviewQuestions: [
      "Qual é a diferença entre chart e release?",
      "Como validar um chart antes do deploy?",
      "Como usar Helm com Argo CD?",
    ],
    related: ["kubernetes", "cicd", "terraform"],
  },
  {
    slug: "aws",
    title: "Amazon Web Services",
    category: "Cloud",
    summary: "Plataforma de cloud pública com serviços de computação, rede, armazenamento, dados e segurança.",
    aliases: ["AWS", "Amazon Cloud"],
    concepts: ["Region", "Availability Zone", "VPC", "IAM", "EC2", "S3", "RDS", "EKS"],
    sections: [
      {
        id: "fundamentos",
        title: "Modelo global e serviços principais",
        level: "Fundamentos",
        summary: "A AWS organiza recursos em regiões e zonas de disponibilidade com responsabilidades compartilhadas.",
        points: [
          "Regiões são áreas geográficas independentes; Availability Zones isolam falhas dentro da região.",
          "IAM controla identidades, roles, políticas e acesso a APIs.",
          "EC2 oferece máquinas virtuais; S3 oferece armazenamento de objetos.",
          "O cliente protege dados, identidades e configurações sob sua responsabilidade.",
        ],
      },
      {
        id: "arquitetura",
        title: "Arquiteturas resilientes",
        level: "Intermediário",
        summary: "Resiliência combina redundância multi-AZ, desacoplamento e recuperação automatizada.",
        points: [
          "Application Load Balancer distribui tráfego HTTP/HTTPS entre targets saudáveis.",
          "Auto Scaling ajusta capacidade de acordo com métricas e políticas.",
          "RDS Multi-AZ aumenta disponibilidade, mas não substitui backups.",
          "SQS desacopla produtores e consumidores para absorver picos.",
        ],
      },
      {
        id: "rede-seguranca",
        title: "Rede e segurança",
        level: "Avançado",
        summary: "VPCs, roteamento e controles de identidade devem ser projetados em conjunto.",
        points: [
          "Subnets públicas e privadas são definidas pelo roteamento, não pelo nome.",
          "Security Groups são stateful; Network ACLs são stateless.",
          "VPC Endpoints permitem acesso privado a serviços suportados.",
          "KMS gerencia chaves e integra criptografia a vários serviços.",
        ],
      },
      {
        id: "especialista",
        title: "Governança e escala",
        level: "Especialista",
        summary: "Ambientes grandes usam múltiplas contas, landing zones, observabilidade e políticas organizacionais.",
        points: [
          "AWS Organizations e SCPs estabelecem limites de governança entre contas.",
          "Transit Gateway centraliza conectividade entre várias VPCs e redes externas.",
          "Well-Architected Framework orienta decisões de segurança, confiabilidade, desempenho, custo e operação.",
          "FinOps relaciona arquitetura, uso e responsabilidade financeira.",
        ],
      },
    ],
    interviewQuestions: [
      "Qual é a diferença entre Security Group e Network ACL?",
      "Como projetar uma aplicação altamente disponível em duas AZs?",
      "Quando usar SQS em vez de comunicação síncrona?",
    ],
    related: ["terraform", "redes", "seguranca", "kubernetes"],
  },
  {
    slug: "azure",
    title: "Microsoft Azure",
    category: "Cloud",
    summary: "Plataforma de cloud da Microsoft para computação, identidade, rede, dados e serviços gerenciados.",
    aliases: ["Azure", "Microsoft Cloud"],
    concepts: ["Subscription", "Resource Group", "VNet", "Entra ID", "VM", "Storage Account", "AKS"],
    sections: [
      {
        id: "fundamentos",
        title: "Organização de recursos",
        level: "Fundamentos",
        summary: "Azure organiza recursos por tenant, subscriptions, resource groups e regiões.",
        points: [
          "Microsoft Entra ID administra identidades e autenticação.",
          "Resource Groups agrupam recursos com ciclo de vida relacionado.",
          "Subscriptions definem limites administrativos, financeiros e de quota.",
          "Azure Resource Manager fornece a camada declarativa de gerenciamento.",
        ],
      },
      {
        id: "servicos",
        title: "Computação e dados",
        level: "Intermediário",
        summary: "Azure oferece máquinas virtuais, plataformas de aplicação, bancos gerenciados e Kubernetes.",
        points: [
          "Virtual Machine Scale Sets automatizam grupos escaláveis de VMs.",
          "App Service hospeda aplicações web sem administração direta do sistema operacional.",
          "Azure SQL oferece banco relacional gerenciado.",
          "AKS fornece Kubernetes gerenciado integrado ao ecossistema Azure.",
        ],
      },
      {
        id: "rede",
        title: "Rede e conectividade",
        level: "Avançado",
        summary: "VNets, NSGs, peering e serviços de entrada formam a base de conectividade.",
        points: [
          "Network Security Groups filtram tráfego por regras de origem, destino, porta e protocolo.",
          "VNet Peering conecta redes virtuais com baixa latência.",
          "Application Gateway oferece balanceamento de camada 7 e integração com WAF.",
          "Private Link expõe serviços por endereços privados dentro da VNet.",
        ],
      },
      {
        id: "especialista",
        title: "Governança empresarial",
        level: "Especialista",
        summary: "Management Groups, Policy e landing zones padronizam ambientes com muitas subscriptions.",
        points: [
          "Azure Policy audita ou bloqueia configurações fora do padrão.",
          "Management Groups aplicam governança hierárquica.",
          "Managed Identities evitam credenciais fixas em aplicações.",
          "Defender for Cloud centraliza recomendações de postura e proteção de workloads.",
        ],
      },
    ],
    interviewQuestions: [
      "Qual é a função de um Resource Group?",
      "Qual é a diferença entre NSG e Azure Firewall?",
      "Como Managed Identities reduzem o uso de secrets?",
    ],
    related: ["terraform", "redes", "seguranca", "kubernetes"],
  },
  {
    slug: "gcp",
    title: "Google Cloud Platform",
    category: "Cloud",
    summary: "Plataforma de cloud do Google com foco em dados, infraestrutura global, Kubernetes e serviços gerenciados.",
    aliases: ["GCP", "Google Cloud"],
    concepts: ["Project", "Organization", "VPC", "IAM", "Compute Engine", "Cloud Storage", "GKE"],
    sections: [
      {
        id: "fundamentos",
        title: "Hierarquia e recursos",
        level: "Fundamentos",
        summary: "Organizações, folders e projects formam a hierarquia administrativa do Google Cloud.",
        points: [
          "Projects isolam billing, APIs, quotas e recursos.",
          "IAM associa principals a roles em níveis da hierarquia.",
          "Regions contêm zones usadas para distribuir workloads.",
          "Cloud Storage fornece armazenamento de objetos durável.",
        ],
      },
      {
        id: "servicos",
        title: "Computação e plataformas",
        level: "Intermediário",
        summary: "Compute Engine, Cloud Run e GKE atendem diferentes níveis de abstração operacional.",
        points: [
          "Compute Engine fornece VMs configuráveis.",
          "Cloud Run executa containers sob demanda com infraestrutura gerenciada.",
          "GKE fornece Kubernetes gerenciado com integrações nativas.",
          "Managed Instance Groups suportam auto scaling e auto healing.",
        ],
      },
      {
        id: "rede-dados",
        title: "Rede global e dados",
        level: "Avançado",
        summary: "A VPC global e os serviços de dados permitem arquiteturas distribuídas entre regiões.",
        points: [
          "VPCs são globais e subnets são regionais.",
          "Cloud Load Balancing oferece opções globais e regionais.",
          "BigQuery executa análise serverless em grandes volumes de dados.",
          "Pub/Sub oferece mensageria assíncrona escalável.",
        ],
      },
      {
        id: "especialista",
        title: "Segurança e organização em escala",
        level: "Especialista",
        summary: "Controles organizacionais, identidade de workload e perímetros de serviço reduzem exposição.",
        points: [
          "Organization Policies restringem configurações em toda a hierarquia.",
          "Workload Identity evita chaves estáticas para aplicações.",
          "VPC Service Controls criam perímetros contra exfiltração de dados em serviços suportados.",
          "Shared VPC centraliza rede enquanto projetos de serviço mantêm autonomia.",
        ],
      },
    ],
    interviewQuestions: [
      "Qual é a diferença entre project e folder?",
      "Por que a VPC do GCP é considerada global?",
      "Quando usar Cloud Run em vez de GKE?",
    ],
    related: ["terraform", "redes", "seguranca", "kubernetes"],
  },
  {
    slug: "terraform",
    title: "Terraform",
    category: "Automação e IaC",
    summary: "Ferramenta declarativa de Infrastructure as Code para provisionar recursos através de providers.",
    aliases: ["IaC", "HashiCorp Terraform"],
    concepts: ["Provider", "Resource", "Data source", "State", "Plan", "Module", "Backend"],
    sections: [
      {
        id: "fundamentos",
        title: "Configuração declarativa",
        level: "Fundamentos",
        summary: "Terraform compara configuração, state e infraestrutura real para construir um plano de mudanças.",
        points: [
          "Providers traduzem recursos Terraform para APIs externas.",
          "Resources descrevem objetos gerenciados; data sources consultam objetos existentes.",
          "terraform plan apresenta mudanças antes da aplicação.",
          "O state relaciona endereços lógicos a recursos reais.",
        ],
      },
      {
        id: "state-modulos",
        title: "State remoto e módulos",
        level: "Intermediário",
        summary: "Equipes precisam de state remoto protegido, locking e módulos com interfaces claras.",
        points: [
          "Backends remotos centralizam state e podem oferecer locking.",
          "State contém metadados sensíveis e deve ser criptografado e controlado.",
          "Módulos encapsulam padrões reutilizáveis por variables e outputs.",
          "Versões de providers e módulos devem ser restringidas deliberadamente.",
        ],
      },
      {
        id: "ciclo",
        title: "Ciclo de vida e refatoração",
        level: "Avançado",
        summary: "Mudanças seguras dependem de entendimento do grafo, dependências e operações sobre state.",
        points: [
          "Terraform infere dependências por referências e permite depends_on quando necessário.",
          "moved blocks preservam identidade durante refatorações.",
          "Import associa infraestrutura existente à configuração.",
          "create_before_destroy e prevent_destroy alteram comportamento do ciclo de vida.",
        ],
      },
      {
        id: "especialista",
        title: "Governança e automação em escala",
        level: "Especialista",
        summary: "Pipelines maduros separam validação, plano, aprovação, aplicação e políticas.",
        points: [
          "Plans devem ser associados ao commit revisado para evitar mudanças inesperadas.",
          "Policy as Code aplica restrições antes do provisionamento.",
          "Estruturas multiambiente devem minimizar duplicação e acoplamento.",
          "Drift deve ser detectado, investigado e corrigido pelo fluxo declarativo.",
        ],
      },
    ],
    interviewQuestions: [
      "Por que o Terraform precisa de state?",
      "Como evitar aplicação concorrente sobre o mesmo state?",
      "Qual é a diferença entre module, resource e data source?",
    ],
    related: ["aws", "azure", "gcp", "cicd", "ansible"],
  },
  {
    slug: "ansible",
    title: "Ansible",
    category: "Automação e IaC",
    summary: "Ferramenta de automação agentless para configuração, orquestração e execução remota.",
    aliases: ["Configuration Management"],
    concepts: ["Inventory", "Playbook", "Task", "Module", "Role", "Handler", "Fact"],
    sections: [
      {
        id: "fundamentos",
        title: "Inventário e playbooks",
        level: "Fundamentos",
        summary: "Ansible conecta-se normalmente por SSH e executa módulos descritos em playbooks YAML.",
        points: [
          "Inventories agrupam hosts e variáveis.",
          "Playbooks associam hosts a listas de tasks.",
          "Modules executam operações idempotentes sempre que possível.",
          "Facts expõem informações coletadas dos sistemas gerenciados.",
        ],
      },
      {
        id: "roles",
        title: "Roles e reutilização",
        level: "Intermediário",
        summary: "Roles organizam tasks, handlers, templates, files e defaults em componentes reutilizáveis.",
        points: [
          "Handlers executam ações condicionadas a mudanças notificadas.",
          "Templates Jinja2 geram arquivos a partir de variáveis.",
          "group_vars e host_vars separam configuração por escopo.",
          "Tags permitem executar subconjuntos controlados do playbook.",
        ],
      },
      {
        id: "seguranca",
        title: "Segredos e execução controlada",
        level: "Avançado",
        summary: "Automação segura exige proteção de credenciais, validação e limitação de impacto.",
        points: [
          "Ansible Vault protege valores em repouso, mas as chaves precisam de gestão adequada.",
          "check mode antecipa mudanças quando o módulo oferece suporte.",
          "serial e estratégias controlam quantos hosts mudam simultaneamente.",
          "become deve ser aplicado apenas às tasks que exigem privilégio elevado.",
        ],
      },
      {
        id: "especialista",
        title: "Automação em larga escala",
        level: "Especialista",
        summary: "Execução em larga escala depende de inventories dinâmicos, observabilidade e testes de roles.",
        points: [
          "Inventories dinâmicos consultam clouds e CMDBs.",
          "Execution environments padronizam coleções e dependências.",
          "Molecule pode testar roles em ambientes descartáveis.",
          "Automação deve produzir logs auditáveis e resultados determinísticos.",
        ],
      },
    ],
    interviewQuestions: [
      "O que significa idempotência no Ansible?",
      "Qual é a diferença entre task, handler e role?",
      "Quando usar Terraform e quando usar Ansible?",
    ],
    related: ["terraform", "linux", "cicd"],
  },
  {
    slug: "cicd",
    title: "CI/CD e GitOps",
    category: "Automação e IaC",
    summary: "Práticas para validar, empacotar, publicar e implantar mudanças de software com rastreabilidade.",
    aliases: ["Continuous Integration", "Continuous Delivery", "GitOps"],
    concepts: ["Pipeline", "Artifact", "Runner", "Deployment", "Rollback", "Argo CD", "GitHub Actions"],
    sections: [
      {
        id: "fundamentos",
        title: "Integração contínua",
        level: "Fundamentos",
        summary: "CI valida cada mudança por build, testes e análise automatizada.",
        points: [
          "Pipelines devem falhar rapidamente em problemas de lint, tipos ou testes.",
          "Artefatos devem ser construídos uma vez e promovidos entre ambientes.",
          "Secrets do pipeline não devem aparecer em logs.",
          "Pull requests estabelecem revisão antes da integração.",
        ],
      },
      {
        id: "entrega",
        title: "Entrega e implantação",
        level: "Intermediário",
        summary: "CD automatiza publicação e deploy com critérios de aprovação e rollback.",
        points: [
          "Tags imutáveis associam uma imagem a um commit específico.",
          "Rolling updates reduzem indisponibilidade durante novas versões.",
          "Health checks impedem promoção de instâncias defeituosas.",
          "Ambientes devem diferir por configuração, não por artefatos recompilados.",
        ],
      },
      {
        id: "gitops",
        title: "GitOps",
        level: "Avançado",
        summary: "No GitOps, o Git contém o estado desejado e um reconciliador aplica mudanças ao ambiente.",
        points: [
          "Argo CD compara manifests desejados com recursos vivos do cluster.",
          "Self-heal corrige drift não autorizado.",
          "Prune remove recursos que deixaram de existir no estado desejado.",
          "O histórico Git fornece auditoria e facilita rollback declarativo.",
        ],
      },
      {
        id: "especialista",
        title: "Segurança da supply chain",
        level: "Especialista",
        summary: "Pipelines maduros verificam origem, conteúdo e promoção dos artefatos.",
        points: [
          "SBOM documenta dependências presentes no artefato.",
          "Assinatura e provenance demonstram como e onde o artefato foi produzido.",
          "OIDC reduz a necessidade de credenciais cloud de longa duração.",
          "Políticas de admissão podem bloquear imagens não aprovadas.",
        ],
      },
    ],
    interviewQuestions: [
      "Qual é a diferença entre continuous delivery e continuous deployment?",
      "Como o Argo CD detecta e corrige drift?",
      "Por que usar tags de imagem imutáveis?",
    ],
    related: ["kubernetes", "helm", "docker", "terraform"],
  },
  {
    slug: "linux",
    title: "Linux",
    category: "Sistemas operacionais",
    summary: "Sistema operacional e ecossistema central em servidores, containers, cloud e plataformas DevOps.",
    aliases: ["GNU/Linux", "Unix-like"],
    concepts: ["Process", "Filesystem", "systemd", "Permission", "Socket", "Namespace", "cgroup"],
    sections: [
      {
        id: "fundamentos",
        title: "Filesystem, usuários e processos",
        level: "Fundamentos",
        summary: "Linux representa muitos recursos como arquivos e organiza execução por processos e permissões.",
        points: [
          "Permissões tradicionais usam owner, group e bits de leitura, escrita e execução.",
          "Processos possuem PID, estado, prioridade e descritores de arquivo.",
          "Diretórios como /etc, /var, /proc e /sys possuem funções distintas.",
          "systemd administra serviços, targets, timers e logs do journal.",
        ],
      },
      {
        id: "recursos",
        title: "CPU, memória e armazenamento",
        level: "Intermediário",
        summary: "Diagnóstico exige distinguir uso real de recursos, cache e limites do sistema.",
        points: [
          "Load average mede tarefas executáveis ou bloqueadas, não apenas uso de CPU.",
          "Memória disponível considera cache recuperável pelo kernel.",
          "Inodes representam metadados de arquivos e podem esgotar antes do espaço em bytes.",
          "Descritores de arquivo limitam sockets, pipes e arquivos abertos por processos.",
        ],
      },
      {
        id: "rede-kernel",
        title: "Rede e kernel",
        level: "Avançado",
        summary: "Ferramentas de rede e interfaces do kernel revelam o caminho das conexões e gargalos.",
        points: [
          "ip substitui ferramentas legadas para endereços, rotas e interfaces.",
          "ss inspeciona sockets e estados TCP.",
          "sysctl altera parâmetros do kernel em runtime.",
          "Namespaces e cgroups formam a base de isolamento de containers.",
        ],
      },
      {
        id: "especialista",
        title: "Observabilidade e análise de desempenho",
        level: "Especialista",
        summary: "Análise profunda correlaciona scheduler, I/O, memória, rede, syscalls e comportamento da aplicação.",
        points: [
          "strace acompanha syscalls e sinais de um processo.",
          "perf analisa eventos de CPU e hotspots.",
          "eBPF permite instrumentação programável com baixo overhead relativo.",
          "Diagnóstico deve confirmar hipóteses com métricas antes de alterar parâmetros.",
        ],
      },
    ],
    interviewQuestions: [
      "O que é um inode e como pode causar filesystem cheio?",
      "Qual é a diferença entre processo e thread?",
      "Como investigar alta carga com CPU aparentemente baixa?",
    ],
    related: ["redes", "docker", "observabilidade", "seguranca"],
  },
  {
    slug: "vmware",
    title: "VMware e virtualização",
    category: "Sistemas operacionais",
    summary: "Virtualização de infraestrutura baseada em hypervisors, máquinas virtuais, rede e armazenamento definidos por software.",
    aliases: ["vSphere", "ESXi", "virtualização"],
    concepts: ["Hypervisor", "VM", "ESXi", "vCenter", "vMotion", "Datastore", "vSwitch"],
    sections: [
      {
        id: "fundamentos",
        title: "Hypervisor e máquinas virtuais",
        level: "Fundamentos",
        summary: "Um hypervisor compartilha hardware físico entre sistemas operacionais isolados.",
        points: [
          "ESXi é o hypervisor bare-metal da plataforma vSphere.",
          "vCenter centraliza administração de hosts e VMs.",
          "Datastores armazenam discos e arquivos das máquinas virtuais.",
          "Snapshots capturam estado para operações temporárias, mas não substituem backup.",
        ],
      },
      {
        id: "cluster",
        title: "Clusters e mobilidade",
        level: "Intermediário",
        summary: "Clusters combinam hosts para disponibilidade, balanceamento e manutenção.",
        points: [
          "vMotion move VMs em execução entre hosts compatíveis.",
          "Storage vMotion move discos virtuais entre datastores.",
          "HA reinicia VMs após falha de host.",
          "DRS recomenda ou executa redistribuição de workloads.",
        ],
      },
      {
        id: "rede-storage",
        title: "Rede e armazenamento",
        level: "Avançado",
        summary: "Desempenho depende de desenho correto de uplinks, port groups, multipathing e capacidade de storage.",
        points: [
          "vSwitches conectam interfaces virtuais a uplinks físicos.",
          "VLANs segmentam tráfego por port groups.",
          "Multipathing aumenta resiliência de acesso ao storage.",
          "Overcommit precisa considerar picos e contenção real de recursos.",
        ],
      },
      {
        id: "especialista",
        title: "Capacidade e troubleshooting",
        level: "Especialista",
        summary: "Investigação especializada distingue consumo da VM, contenção no host e latência da infraestrutura.",
        points: [
          "CPU Ready indica tempo aguardando escalonamento no hypervisor.",
          "Ballooning e swapping sinalizam pressão de memória em diferentes níveis.",
          "Latência de storage deve ser decomposta entre guest, kernel e dispositivo.",
          "Mudanças devem considerar compatibilidade de hardware, versões e dependências do cluster.",
        ],
      },
    ],
    interviewQuestions: [
      "Qual é a diferença entre HA, DRS e vMotion?",
      "Por que snapshot não substitui backup?",
      "O que CPU Ready indica?",
    ],
    related: ["linux", "redes", "observabilidade"],
  },
  {
    slug: "redes",
    title: "Redes de computadores",
    category: "Redes e segurança",
    summary: "Princípios de comunicação entre sistemas, incluindo endereçamento, roteamento, transporte, DNS e HTTP.",
    aliases: ["Networking", "TCP/IP"],
    concepts: ["Ethernet", "ARP", "IP", "Routing", "TCP", "UDP", "DNS", "HTTP", "NAT"],
    sections: [
      {
        id: "fundamentos",
        title: "Camadas e endereçamento",
        level: "Fundamentos",
        summary: "Comunicação em rede combina encapsulamento, endereços locais, endereços IP e rotas.",
        points: [
          "Ethernet entrega frames dentro do domínio local.",
          "ARP resolve IPv4 para endereços MAC na rede local.",
          "IP identifica origem e destino entre redes.",
          "A tabela de rotas decide o próximo salto de cada pacote.",
        ],
      },
      {
        id: "transporte",
        title: "TCP, UDP, DNS e HTTP",
        level: "Intermediário",
        summary: "Protocolos de transporte e aplicação oferecem diferentes garantias e modelos de comunicação.",
        points: [
          "TCP oferece fluxo confiável, ordenado e orientado a conexão.",
          "UDP reduz overhead e deixa confiabilidade para a aplicação quando necessária.",
          "DNS traduz nomes em registros como A, AAAA, CNAME e MX.",
          "HTTP modela requisições, respostas, métodos, headers e status codes.",
        ],
      },
      {
        id: "infraestrutura",
        title: "Roteamento, NAT e balanceamento",
        level: "Avançado",
        summary: "Infraestruturas modernas combinam múltiplas rotas, traduções e proxies em diferentes camadas.",
        points: [
          "NAT altera endereços ou portas durante o encaminhamento.",
          "Load balancers de camada 4 operam sobre conexões; camada 7 interpreta protocolos de aplicação.",
          "Anycast anuncia o mesmo endereço por múltiplos locais.",
          "MTU incorreta pode causar fragmentação, perda ou falhas aparentemente seletivas.",
        ],
      },
      {
        id: "especialista",
        title: "Troubleshooting sistemático",
        level: "Especialista",
        summary: "Diagnóstico confiável segue o caminho do pacote e testa cada hipótese na camada adequada.",
        points: [
          "tcpdump confirma o que realmente entra e sai de uma interface.",
          "traceroute ajuda a observar saltos, mas firewalls podem limitar a interpretação.",
          "Estados TCP distinguem falha de DNS, conexão, handshake ou aplicação.",
          "Métricas de perda, retransmissão, latência e jitter devem ser correlacionadas.",
        ],
      },
    ],
    interviewQuestions: [
      "Explique o handshake TCP de três vias.",
      "Qual é a diferença entre load balancer L4 e L7?",
      "Como investigar uma aplicação que responde por IP, mas não por nome?",
    ],
    related: ["seguranca", "linux", "kubernetes", "sistemas-distribuidos"],
  },
  {
    slug: "seguranca",
    title: "Segurança e protocolos",
    category: "Redes e segurança",
    summary: "Princípios e protocolos para proteger identidade, comunicação, dados e infraestrutura.",
    aliases: ["Cybersecurity", "TLS", "OAuth 2.0", "Zero Trust"],
    concepts: ["CIA", "TLS", "PKI", "OAuth 2.0", "OIDC", "RBAC", "Encryption", "Zero Trust"],
    sections: [
      {
        id: "fundamentos",
        title: "Princípios básicos",
        level: "Fundamentos",
        summary: "Confidencialidade, integridade e disponibilidade orientam controles técnicos e operacionais.",
        points: [
          "Autenticação verifica identidade; autorização decide o que a identidade pode fazer.",
          "Criptografia em trânsito e em repouso protege dados em contextos diferentes.",
          "Privilégio mínimo reduz impacto de credenciais comprometidas.",
          "Defesa em profundidade combina controles independentes.",
        ],
      },
      {
        id: "protocolos",
        title: "TLS, certificados e identidade",
        level: "Intermediário",
        summary: "TLS usa criptografia e certificados para autenticar endpoints e proteger o canal.",
        points: [
          "PKI relaciona certificados, autoridades certificadoras e cadeias de confiança.",
          "TLS negocia parâmetros e estabelece chaves de sessão.",
          "OAuth 2.0 delega autorização; OpenID Connect adiciona identidade.",
          "Tokens devem ter escopo e validade mínimos necessários.",
        ],
      },
      {
        id: "arquitetura",
        title: "Arquitetura segura",
        level: "Avançado",
        summary: "Segurança deve ser incorporada a identidade, rede, workloads, dados e supply chain.",
        points: [
          "Segmentação limita movimentos laterais.",
          "Gestores de secrets evitam credenciais embutidas em código e imagens.",
          "WAF protege padrões HTTP conhecidos, mas não substitui correções na aplicação.",
          "Logs de auditoria precisam ser centralizados e protegidos contra alteração.",
        ],
      },
      {
        id: "especialista",
        title: "Threat modeling e resposta",
        level: "Especialista",
        summary: "Maturidade exige modelar ameaças, priorizar riscos e responder com evidências verificáveis.",
        points: [
          "Threat modeling identifica ativos, fronteiras de confiança, ameaças e mitigação.",
          "Zero Trust exige verificação contínua, contexto e acesso mínimo.",
          "Resposta a incidentes preserva evidências e reduz contenção impulsiva.",
          "Controles devem ser avaliados por eficácia real, não apenas por presença documental.",
        ],
      },
    ],
    interviewQuestions: [
      "Qual é a diferença entre OAuth 2.0 e OpenID Connect?",
      "Como funciona uma cadeia de confiança de certificados?",
      "O que significa Zero Trust na prática?",
    ],
    related: ["redes", "linux", "kubernetes", "cicd"],
  },
  {
    slug: "kafka",
    title: "Apache Kafka",
    category: "Dados e sistemas distribuídos",
    summary: "Plataforma distribuída de eventos baseada em logs particionados, replicados e duráveis.",
    aliases: ["Event streaming", "distributed log"],
    concepts: ["Broker", "Topic", "Partition", "Offset", "Producer", "Consumer Group", "Replication"],
    sections: [
      {
        id: "fundamentos",
        title: "Topics, partitions e offsets",
        level: "Fundamentos",
        summary: "Kafka armazena eventos em topics divididos em partitions ordenadas.",
        points: [
          "Cada evento recebe um offset dentro da partition.",
          "A ordem é garantida apenas dentro da mesma partition.",
          "Producers publicam eventos; consumers leem no próprio ritmo.",
          "Retenção permite reler eventos durante o período configurado.",
        ],
      },
      {
        id: "consumo",
        title: "Consumer groups e escala",
        level: "Intermediário",
        summary: "Consumer groups distribuem partitions entre consumidores para processamento paralelo.",
        points: [
          "Uma partition é atribuída a no máximo um consumer por group em um dado momento.",
          "Mais consumers que partitions não aumentam paralelismo do grupo.",
          "Commits de offset registram progresso de consumo.",
          "Rebalances redistribuem partitions quando membros entram ou saem.",
        ],
      },
      {
        id: "confiabilidade",
        title: "Replicação e garantias",
        level: "Avançado",
        summary: "Durabilidade depende de replicação, acknowledgements e configuração do conjunto in-sync.",
        points: [
          "Cada partition possui leader e replicas.",
          "acks=all aumenta garantia de escrita quando combinado com min.insync.replicas.",
          "Idempotent producers reduzem duplicações causadas por retries.",
          "Exactly-once exige condições específicas e não elimina todos os efeitos externos duplicados.",
        ],
      },
      {
        id: "especialista",
        title: "Desempenho e operação",
        level: "Especialista",
        summary: "Operação especializada equilibra throughput, latência, retenção, tamanho de mensagens e capacidade de storage.",
        points: [
          "Partition count influencia paralelismo, metadados e custo de rebalance.",
          "Batching e compressão aumentam eficiência de rede e disco.",
          "Consumer lag indica atraso, mas precisa ser interpretado com taxa de produção.",
          "Hot partitions podem surgir por chaves de distribuição inadequadas.",
        ],
      },
    ],
    interviewQuestions: [
      "Como o Kafka preserva ordem de mensagens?",
      "O que acontece quando existem mais consumers do que partitions?",
      "Como a configuração acks se relaciona com durabilidade?",
    ],
    related: ["sistemas-distribuidos", "redis", "observabilidade"],
  },
  {
    slug: "redis",
    title: "Redis",
    category: "Dados e sistemas distribuídos",
    summary: "Data store em memória usado para cache, sessões, estruturas de dados, filas leves e coordenação.",
    aliases: ["in-memory data store", "cache"],
    concepts: ["Key", "TTL", "String", "Hash", "Set", "Sorted Set", "Replication", "Cluster"],
    sections: [
      {
        id: "fundamentos",
        title: "Estruturas e expiração",
        level: "Fundamentos",
        summary: "Redis associa chaves a estruturas de dados e pode expirá-las automaticamente por TTL.",
        points: [
          "Strings armazenam valores simples, contadores e blobs.",
          "Hashes representam conjuntos de campos.",
          "Sets e sorted sets suportam associação e ranking.",
          "TTL é essencial para caches e dados temporários.",
        ],
      },
      {
        id: "cache",
        title: "Padrões de cache",
        level: "Intermediário",
        summary: "Caches melhoram latência, mas introduzem invalidação, consistência e risco de stampede.",
        points: [
          "Cache-aside carrega dados sob demanda e atualiza o cache após miss.",
          "TTL deve refletir tolerância a dados desatualizados.",
          "Jitter reduz expirações simultâneas de muitas chaves.",
          "Locks ou single-flight podem reduzir cache stampede.",
        ],
      },
      {
        id: "alta-disponibilidade",
        title: "Persistência e alta disponibilidade",
        level: "Avançado",
        summary: "Redis pode combinar snapshots, append-only file, replicas e Sentinel ou Cluster.",
        points: [
          "RDB produz snapshots periódicos.",
          "AOF registra operações para reconstrução mais granular.",
          "Sentinel monitora instâncias e coordena failover em topologias não clusterizadas.",
          "Redis Cluster distribui slots de chaves entre shards.",
        ],
      },
      {
        id: "especialista",
        title: "Memória e consistência operacional",
        level: "Especialista",
        summary: "Desempenho depende do tamanho das estruturas, políticas de eviction e comportamento das operações.",
        points: [
          "maxmemory e eviction policy definem comportamento sob pressão.",
          "Comandos O(N) podem bloquear o event loop em datasets grandes.",
          "Hot keys concentram tráfego e limitam escala horizontal.",
          "Replicação assíncrona implica janelas possíveis de perda durante failover.",
        ],
      },
    ],
    interviewQuestions: [
      "Quando usar Redis como cache e quando não usar?",
      "Qual é a diferença entre Sentinel e Redis Cluster?",
      "Como evitar cache stampede?",
    ],
    related: ["sistemas-distribuidos", "kafka", "observabilidade"],
  },
  {
    slug: "sistemas-distribuidos",
    title: "Sistemas distribuídos",
    category: "Dados e sistemas distribuídos",
    summary: "Sistemas compostos por múltiplos processos ou nós que cooperam sob latência, concorrência e falhas parciais.",
    aliases: ["Distributed systems"],
    concepts: ["Consistency", "Availability", "Partition", "Consensus", "Replication", "Quorum", "Idempotency"],
    sections: [
      {
        id: "fundamentos",
        title: "Falhas parciais e tempo",
        level: "Fundamentos",
        summary: "Em sistemas distribuídos, componentes podem falhar ou atrasar sem que todos observem o mesmo estado.",
        points: [
          "Latência é variável e timeouts não provam definitivamente que o outro lado falhou.",
          "Mensagens podem ser perdidas, duplicadas, atrasadas ou reordenadas.",
          "Relógios de máquinas diferentes não são perfeitamente sincronizados.",
          "Retries precisam considerar idempotência.",
        ],
      },
      {
        id: "consistencia",
        title: "Consistência e replicação",
        level: "Intermediário",
        summary: "Replicação melhora disponibilidade e leitura, mas exige regras para convergência e conflitos.",
        points: [
          "Strong consistency apresenta uma visão única sob condições definidas.",
          "Eventual consistency permite divergência temporária entre replicas.",
          "Leader-based replication centraliza a ordem de escritas.",
          "Quorums relacionam número de replicas, leituras e escritas.",
        ],
      },
      {
        id: "consenso",
        title: "Consenso e particionamento",
        level: "Avançado",
        summary: "Protocolos de consenso permitem concordar sobre uma sequência mesmo com falhas limitadas.",
        points: [
          "Raft organiza leader election, log replication e commit por maioria.",
          "CAP descreve escolhas durante partições de rede, não um menu permanente de duas letras.",
          "Sharding distribui dados, mas cria desafios de roteamento e operações entre partitions.",
          "Rebalanceamento move responsabilidade e pode afetar latência e disponibilidade.",
        ],
      },
      {
        id: "especialista",
        title: "Semântica de entrega e desenho de falhas",
        level: "Especialista",
        summary: "Arquiteturas robustas assumem duplicação, retry, backpressure e degradação controlada.",
        points: [
          "At-most-once, at-least-once e exactly-once descrevem garantias diferentes.",
          "Outbox pattern coordena gravação de estado e publicação de eventos.",
          "Circuit breakers limitam chamadas a dependências degradadas.",
          "Chaos engineering testa hipóteses de resiliência em condições controladas.",
        ],
      },
    ],
    interviewQuestions: [
      "O que é uma falha parcial?",
      "Como quorum se relaciona com consistência e disponibilidade?",
      "Por que exactly-once é uma afirmação que precisa de contexto?",
    ],
    related: ["kafka", "redis", "redes", "observabilidade"],
  },
  {
    slug: "observabilidade",
    title: "Observabilidade",
    category: "Operações e confiabilidade",
    summary: "Capacidade de compreender o estado interno de um sistema a partir de sinais externos como métricas, logs e traces.",
    aliases: ["Monitoring", "Telemetry", "OpenTelemetry"],
    concepts: ["Metrics", "Logs", "Traces", "SLI", "SLO", "Alert", "Correlation", "OpenTelemetry"],
    sections: [
      {
        id: "fundamentos",
        title: "Métricas, logs e traces",
        level: "Fundamentos",
        summary: "Cada sinal responde a perguntas diferentes e ganha valor quando pode ser correlacionado.",
        points: [
          "Métricas resumem comportamento numérico ao longo do tempo.",
          "Logs registram eventos discretos com contexto.",
          "Traces acompanham uma requisição através de múltiplos serviços.",
          "Labels e atributos de alta cardinalidade exigem controle.",
        ],
      },
      {
        id: "sli-slo",
        title: "SLIs, SLOs e alertas",
        level: "Intermediário",
        summary: "Objetivos devem medir a experiência real do utilizador e orientar alertas acionáveis.",
        points: [
          "SLI é uma medida; SLO define a meta dessa medida.",
          "Error budget representa a margem de falha tolerada pelo objetivo.",
          "Alertas devem indicar ação possível, não apenas anomalia estatística.",
          "Latência deve ser analisada por percentis, não apenas médias.",
        ],
      },
      {
        id: "instrumentacao",
        title: "Instrumentação distribuída",
        level: "Avançado",
        summary: "Context propagation e convenções consistentes conectam sinais entre serviços.",
        points: [
          "Trace IDs e span IDs correlacionam operações distribuídas.",
          "OpenTelemetry padroniza APIs, SDKs e coleta de telemetria.",
          "Sampling reduz custo de traces, mas afeta visibilidade.",
          "Exemplars conectam métricas agregadas a traces específicos.",
        ],
      },
      {
        id: "especialista",
        title: "Diagnóstico e custo",
        level: "Especialista",
        summary: "Observabilidade madura equilibra cobertura, retenção, cardinalidade, custo e tempo de investigação.",
        points: [
          "RED mede rate, errors e duration em serviços orientados a requisições.",
          "USE mede utilization, saturation e errors em recursos.",
          "Dashboards devem refletir modelos operacionais, não coleções aleatórias de gráficos.",
          "Telemetria precisa de governança para evitar custos e dados sensíveis desnecessários.",
        ],
      },
    ],
    interviewQuestions: [
      "Qual é a diferença entre monitoramento e observabilidade?",
      "O que são SLI, SLO e error budget?",
      "Quando usar RED e quando usar USE?",
    ],
    related: ["linux", "kubernetes", "sistemas-distribuidos", "cicd"],
  },
];

export const wikiArticleBySlug = Object.fromEntries(
  wikiArticles.map((article) => [article.slug, article]),
) as Record<string, WikiArticle>;

export const wikiCategories = Array.from(new Set(wikiArticles.map((article) => article.category)));
