'use client';

import { useState, type ReactNode } from 'react';
import { getApiArchitectureDiagram, type ApiArchitectureKey } from '@/content/api-architecture-diagrams';
import { getApiPerformanceDiagram, type ApiPerformanceKey } from '@/content/api-performance-diagrams';
import { getApiSecurityDiagram, type ApiSecurityKey } from '@/content/api-security-diagrams';
import { TopicDiagram } from './topic-diagram';
import { useLanguage } from './language-provider';

type Bilingual = { pt: string; en: string };
type GuideCard<K extends string> = { key: K; title: string; subtitle: Bilingual; explanation: Bilingual; steps: Bilingual[]; bestFor?: Bilingual; warning?: Bilingual };

const architectures: GuideCard<ApiArchitectureKey>[] = [
  { key:'rest', title:'RESTful', subtitle:{pt:'Recursos + HTTP + representações',en:'Resources + HTTP + representations'}, explanation:{pt:'REST modela o domínio como recursos identificados por URIs. Em APIs HTTP, métodos como GET, POST, PUT, PATCH e DELETE expressam a intenção e status codes comunicam o resultado.',en:'REST models the domain as resources identified by URIs. In HTTP APIs, methods such as GET, POST, PUT, PATCH, and DELETE express intent while status codes communicate the result.'}, steps:[{pt:'O cliente identifica um recurso, por exemplo /orders/42.',en:'The client identifies a resource, for example /orders/42.'},{pt:'Escolhe o método HTTP que representa a operação.',en:'It selects the HTTP method that represents the operation.'},{pt:'A API autentica, autoriza e valida a requisição.',en:'The API authenticates, authorizes, and validates the request.'},{pt:'A aplicação executa a regra de negócio e acessa dependências.',en:'The application executes business logic and accesses dependencies.'},{pt:'A API retorna status, headers e uma representação como JSON.',en:'The API returns status, headers, and a representation such as JSON.'}],bestFor:{pt:'APIs públicas, CRUD, integrações web e serviços com semântica HTTP clara.',en:'Public APIs, CRUD, web integrations, and services with clear HTTP semantics.'}},
  { key:'graphql', title:'GraphQL', subtitle:{pt:'Query declarativa e schema tipado',en:'Declarative query and typed schema'}, explanation:{pt:'GraphQL expõe um schema e normalmente um endpoint. O cliente escolhe campos e relações, reduzindo over-fetching, mas o servidor precisa controlar complexidade, autorização por campo e problemas N+1.',en:'GraphQL exposes a schema and usually a single endpoint. Clients select fields and relationships, reducing over-fetching, but servers must control query complexity, field authorization, and N+1 problems.'}, steps:[{pt:'O cliente envia uma query indicando os campos necessários.',en:'The client sends a query declaring the required fields.'},{pt:'O servidor faz parse e valida contra o schema.',en:'The server parses and validates it against the schema.'},{pt:'Resolvers executam cada parte do grafo.',en:'Resolvers execute each part of the graph.'},{pt:'Resolvers consultam APIs, caches ou databases.',en:'Resolvers query APIs, caches, or databases.'},{pt:'A resposta JSON mantém a forma da query.',en:'The JSON response follows the shape of the query.'}],bestFor:{pt:'Frontends com necessidades de dados variadas e domínio naturalmente em grafo.',en:'Frontends with variable data needs and naturally graph-shaped domains.'}},
  { key:'grpc', title:'gRPC', subtitle:{pt:'RPC tipado + Protobuf + HTTP/2',en:'Typed RPC + Protobuf + HTTP/2'}, explanation:{pt:'gRPC define contratos em .proto e gera stubs de cliente/servidor. Protocol Buffers reduzem payload e HTTP/2 suporta multiplexing e streaming.',en:'gRPC defines contracts in .proto files and generates client/server stubs. Protocol Buffers reduce payload size and HTTP/2 supports multiplexing and streaming.'}, steps:[{pt:'O serviço e mensagens são definidos em .proto.',en:'The service and messages are defined in .proto.'},{pt:'O tooling gera stubs tipados.',en:'Tooling generates typed stubs.'},{pt:'O cliente chama um método remoto pelo stub.',en:'The client calls a remote method through the stub.'},{pt:'A chamada trafega em frames HTTP/2/Protobuf.',en:'The call travels as HTTP/2/Protobuf frames.'},{pt:'O servidor executa a implementação e retorna uma resposta ou stream.',en:'The server executes the implementation and returns a response or stream.'}],bestFor:{pt:'Comunicação service-to-service de baixa latência e contratos fortes.',en:'Low-latency service-to-service communication with strong contracts.'}},
  { key:'soap', title:'SOAP', subtitle:{pt:'XML + WSDL + contratos enterprise',en:'XML + WSDL + enterprise contracts'}, explanation:{pt:'SOAP define um envelope XML formal e possui extensões maduras para segurança, transações e confiabilidade. É mais verboso, mas ainda comum em integrações enterprise e legadas.',en:'SOAP defines a formal XML envelope and has mature extensions for security, transactions, and reliability. It is more verbose but remains common in enterprise and legacy integrations.'}, steps:[{pt:'O contrato WSDL descreve operações e tipos.',en:'The WSDL contract describes operations and types.'},{pt:'O cliente monta um SOAP Envelope XML.',en:'The client builds a SOAP XML Envelope.'},{pt:'Headers podem carregar segurança e metadados WS-*.',en:'Headers can carry security and WS-* metadata.'},{pt:'O endpoint executa a operação contratada.',en:'The endpoint executes the contracted operation.'},{pt:'O resultado retorna como SOAP response ou SOAP Fault.',en:'The result returns as a SOAP response or SOAP Fault.'}],bestFor:{pt:'Integrações enterprise com contratos rígidos, especialmente ecossistemas legados.',en:'Enterprise integrations with strict contracts, especially legacy ecosystems.'}},
  { key:'websocket', title:'WebSocket', subtitle:{pt:'Canal persistente full-duplex',en:'Persistent full-duplex channel'}, explanation:{pt:'WebSocket começa com um handshake HTTP e depois mantém uma conexão persistente na qual ambos os lados podem enviar frames a qualquer momento.',en:'WebSocket starts with an HTTP handshake and then maintains a persistent connection where both sides can send frames at any time.'}, steps:[{pt:'Cliente abre conexão HTTP e solicita Upgrade.',en:'The client opens an HTTP connection and requests Upgrade.'},{pt:'Servidor aceita com 101 Switching Protocols.',en:'The server accepts with 101 Switching Protocols.'},{pt:'A conexão permanece aberta.',en:'The connection remains open.'},{pt:'Cliente e servidor enviam frames independentemente.',en:'Client and server send frames independently.'},{pt:'Heartbeat, reconnect e backpressure precisam ser projetados.',en:'Heartbeat, reconnect, and backpressure must be designed.'}],bestFor:{pt:'Chat, colaboração, jogos, dashboards e atualizações bidirecionais em tempo real.',en:'Chat, collaboration, games, dashboards, and real-time bidirectional updates.'}},
  { key:'webhook', title:'Webhook', subtitle:{pt:'Callback HTTP disparado por evento',en:'Event-triggered HTTP callback'}, explanation:{pt:'Webhook inverte o polling: quando um evento acontece, o produtor envia um POST para uma URL registrada pelo consumidor.',en:'A webhook reverses polling: when an event occurs, the producer sends a POST to a URL registered by the consumer.'}, steps:[{pt:'Consumidor registra a callback URL.',en:'The consumer registers a callback URL.'},{pt:'O produtor detecta um evento relevante.',en:'The producer detects a relevant event.'},{pt:'Produtor envia POST com event ID e assinatura.',en:'The producer sends a POST with an event ID and signature.'},{pt:'Consumidor valida assinatura e responde rapidamente.',en:'The consumer validates the signature and responds quickly.'},{pt:'Processamento pesado segue assíncrono e idempotente.',en:'Heavy processing continues asynchronously and idempotently.'}],bestFor:{pt:'Notificações SaaS, pagamentos, CI/CD e integração orientada a eventos.',en:'SaaS notifications, payments, CI/CD, and event-driven integration.'}},
  { key:'mqtt', title:'MQTT', subtitle:{pt:'Publish/subscribe leve para dispositivos',en:'Lightweight publish/subscribe for devices'}, explanation:{pt:'MQTT usa broker, tópicos e QoS. É desenhado para links limitados e dispositivos, com baixo overhead e desacoplamento entre publishers e subscribers.',en:'MQTT uses a broker, topics, and QoS. It is designed for constrained links and devices, with low overhead and decoupling between publishers and subscribers.'}, steps:[{pt:'Subscriber registra interesse em um tópico.',en:'A subscriber registers interest in a topic.'},{pt:'Publisher envia PUBLISH para o broker.',en:'A publisher sends PUBLISH to the broker.'},{pt:'Broker aplica topic matching e QoS.',en:'The broker applies topic matching and QoS.'},{pt:'Broker entrega a cada subscriber correspondente.',en:'The broker delivers to matching subscribers.'},{pt:'QoS/retained/session definem comportamento de entrega.',en:'QoS/retained/session settings define delivery behavior.'}],bestFor:{pt:'IoT, telemetria, dispositivos e redes com banda/energia restritas.',en:'IoT, telemetry, devices, and bandwidth/energy-constrained networks.'}},
  { key:'amqp', title:'AMQP', subtitle:{pt:'Messaging confiável e interoperável',en:'Reliable interoperable messaging'}, explanation:{pt:'AMQP é um protocolo de messaging voltado a entrega confiável e interoperabilidade. Brokers normalmente combinam routing, queues, acknowledgements e políticas de retry/DLQ.',en:'AMQP is a messaging protocol focused on reliable delivery and interoperability. Brokers commonly combine routing, queues, acknowledgements, and retry/DLQ policies.'}, steps:[{pt:'Producer publica uma mensagem.',en:'The producer publishes a message.'},{pt:'Router/exchange decide o destino.',en:'A router/exchange determines the destination.'},{pt:'A queue armazena enquanto o consumer não processa.',en:'A queue stores the message until the consumer processes it.'},{pt:'Consumer recebe e ACK/NACK.',en:'The consumer receives and ACKs/NACKs.'},{pt:'Falhas podem seguir retry ou DLQ.',en:'Failures can follow retry or DLQ policies.'}],bestFor:{pt:'Enterprise messaging, workflows assíncronos e integrações que precisam de filas e confirmação.',en:'Enterprise messaging, asynchronous workflows, and integrations requiring queues and acknowledgements.'}},
];

const performance: GuideCard<ApiPerformanceKey>[] = [
  {key:'pagination',title:'Paginação',subtitle:{pt:'Limite o dataset por request',en:'Bound the dataset per request'},explanation:{pt:'Não retorne milhares de objetos quando o cliente usa apenas dezenas. Cursor/keyset pagination costuma ser mais estável que offset em datasets grandes e mutáveis.',en:'Do not return thousands of objects when the client uses only dozens. Cursor/keyset pagination is usually more stable than offset pagination on large, changing datasets.'},steps:[{pt:'Cliente envia limit e cursor.',en:'Client sends limit and cursor.'},{pt:'API impõe limite máximo.',en:'API enforces a maximum limit.'},{pt:'Database usa índice para buscar apenas a próxima página.',en:'Database uses an index to fetch only the next page.'},{pt:'Resposta inclui items e nextCursor.',en:'Response includes items and nextCursor.'}]},
  {key:'caching',title:'Caching',subtitle:{pt:'Evite repetir trabalho caro',en:'Avoid repeating expensive work'},explanation:{pt:'Use HTTP caching, CDN, reverse proxy ou cache de aplicação conforme o dado. Defina chave, TTL, invalidação, consistência e impacto de dados privados.',en:'Use HTTP caching, CDN, reverse proxy, or application caching depending on the data. Define key, TTL, invalidation, consistency, and private-data impact.'},steps:[{pt:'Request procura uma cache key.',en:'Request looks up a cache key.'},{pt:'Em HIT, resposta evita backend.',en:'On HIT, the response bypasses the backend.'},{pt:'Em MISS, API consulta origem.',en:'On MISS, the API queries the origin.'},{pt:'Resultado é armazenado com TTL/política.',en:'Result is stored with TTL/policy.'}]},
  {key:'compression',title:'Payload compression',subtitle:{pt:'Menos bytes na rede',en:'Fewer bytes on the wire'},explanation:{pt:'gzip/Brotli reduzem payloads textuais grandes. Compressão troca CPU por banda e não deve ser aplicada indiscriminadamente a payloads pequenos ou já comprimidos.',en:'gzip/Brotli reduce large textual payloads. Compression trades CPU for bandwidth and should not be applied indiscriminately to small or already-compressed payloads.'},steps:[{pt:'Cliente anuncia Accept-Encoding.',en:'Client advertises Accept-Encoding.'},{pt:'Servidor escolhe algoritmo suportado.',en:'Server selects a supported algorithm.'},{pt:'Payload é comprimido.',en:'Payload is compressed.'},{pt:'Content-Encoding informa como descomprimir.',en:'Content-Encoding tells the client how to decompress.'}]},
  {key:'connection-pool',title:'Connection pool',subtitle:{pt:'Reutilize conexões com DB/upstreams',en:'Reuse DB/upstream connections'},explanation:{pt:'Criar uma conexão de database ou TLS para cada request desperdiça tempo e recursos. Pools limitam concorrência e reutilizam conexões existentes.',en:'Creating a database or TLS connection for every request wastes time and resources. Pools bound concurrency and reuse existing connections.'},steps:[{pt:'Request chega ao worker.',en:'Request reaches a worker.'},{pt:'Worker pede uma conexão ao pool.',en:'Worker borrows a connection from the pool.'},{pt:'Pool reutiliza conexão existente.',en:'Pool reuses an existing connection.'},{pt:'Após uso, a conexão volta ao pool.',en:'After use, the connection returns to the pool.'}]},
  {key:'async-logging',title:'Async logging',subtitle:{pt:'Tire I/O de logs do request path',en:'Remove log I/O from the request path'},explanation:{pt:'Logs remotos síncronos aumentam tail latency e transformam o sistema de logs em dependência da API. Prefira buffer/agent local e envio assíncrono.',en:'Synchronous remote logging increases tail latency and turns the logging system into an API dependency. Prefer a local buffer/agent and asynchronous shipping.'},steps:[{pt:'API processa a requisição.',en:'API processes the request.'},{pt:'Resposta segue sem esperar backend de logs.',en:'Response proceeds without waiting for the logging backend.'},{pt:'Evento vai para buffer/agent.',en:'Event goes to a buffer/agent.'},{pt:'Pipeline envia em batch de forma assíncrona.',en:'Pipeline ships batches asynchronously.'}]},
  {key:'multiplexing',title:'Keep-alive / HTTP/2',subtitle:{pt:'Reduza handshakes e multiplexe streams',en:'Reduce handshakes and multiplex streams'},explanation:{pt:'Reutilizar conexões reduz handshake TCP/TLS. HTTP/2 permite múltiplos streams na mesma conexão; HTTP/3 usa QUIC e reduz interferência entre streams no transporte.',en:'Connection reuse reduces TCP/TLS handshakes. HTTP/2 allows multiple streams on one connection; HTTP/3 uses QUIC and reduces transport-level interference between streams.'},steps:[{pt:'Cliente mantém conexão persistente.',en:'Client keeps a persistent connection.'},{pt:'Vários requests usam a mesma sessão.',en:'Multiple requests share the same session.'},{pt:'HTTP/2 multiplexa streams concorrentes.',en:'HTTP/2 multiplexes concurrent streams.'},{pt:'Menos conexões reduzem custo e pressão em sockets.',en:'Fewer connections reduce cost and socket pressure.'}]},
  {key:'async-processing',title:'Processamento assíncrono',subtitle:{pt:'202 + queue para trabalhos longos',en:'202 + queue for long-running work'},explanation:{pt:'Não mantenha uma conexão HTTP aberta por minutos para tarefas que podem ser jobs. Valide, enfileire, retorne 202 e exponha status/callback.',en:'Do not keep an HTTP connection open for minutes for work that can become a job. Validate, enqueue, return 202, and expose status/callback.'},steps:[{pt:'Cliente envia o comando.',en:'Client sends the command.'},{pt:'API valida e grava/enfileira o job.',en:'API validates and persists/enqueues the job.'},{pt:'API retorna 202 + jobId.',en:'API returns 202 + jobId.'},{pt:'Worker processa fora do request path.',en:'Worker processes outside the request path.'}]},
  {key:'rate-limit',title:'Rate limiting / backpressure',subtitle:{pt:'Proteja capacidade antes da saturação',en:'Protect capacity before saturation'},explanation:{pt:'Rate limit por identidade/tenant evita que um consumidor esgote recursos compartilhados. Combine 429/Retry-After com quotas, concurrency limits e load shedding.',en:'Rate limiting by identity/tenant prevents one consumer from exhausting shared resources. Combine 429/Retry-After with quotas, concurrency limits, and load shedding.'},steps:[{pt:'Gateway identifica consumidor.',en:'Gateway identifies the consumer.'},{pt:'Rate limiter verifica quota.',en:'Rate limiter checks quota.'},{pt:'Dentro do orçamento, request segue.',en:'Within budget, the request proceeds.'},{pt:'Acima do limite, retorna 429 e o cliente recua.',en:'Over the limit, it returns 429 and the client backs off.'}]},
];

const security: GuideCard<ApiSecurityKey>[] = [
  {key:'tls',title:'TLS / HTTPS',subtitle:{pt:'Confidencialidade e identidade do endpoint',en:'Confidentiality and endpoint identity'},explanation:{pt:'TLS protege dados em trânsito, mas não substitui autorização. Valide cadeia, hostname/SAN, validade e use versões/ciphers modernos.',en:'TLS protects data in transit but does not replace authorization. Validate chain, hostname/SAN, validity, and use modern protocol versions/ciphers.'},steps:[{pt:'Cliente inicia handshake.',en:'Client starts the handshake.'},{pt:'Servidor apresenta certificado.',en:'Server presents its certificate.'},{pt:'Cliente valida CA, hostname e validade.',en:'Client validates CA, hostname, and validity.'},{pt:'Chaves de sessão protegem request/response.',en:'Session keys protect requests/responses.'}]},
  {key:'identity',title:'OAuth 2.0 / OIDC / tokens',subtitle:{pt:'Autenticação separada da autorização',en:'Separate authentication from authorization'},explanation:{pt:'OIDC fornece identidade; OAuth 2.0 delega autorização. APIs devem validar assinatura, issuer, audience, expiração, scopes/claims e autorização no recurso.',en:'OIDC provides identity; OAuth 2.0 delegates authorization. APIs must validate signature, issuer, audience, expiration, scopes/claims, and resource-level authorization.'},steps:[{pt:'Cliente autentica no IdP.',en:'Client authenticates with the IdP.'},{pt:'IdP emite token curto.',en:'IdP issues a short-lived token.'},{pt:'Cliente envia token à API.',en:'Client sends the token to the API.'},{pt:'API valida token e policy antes do recurso.',en:'API validates token and policy before the resource.'}]},
  {key:'gateway',title:'API Gateway / WAF',subtitle:{pt:'Policy no edge sem concentrar regra de negócio',en:'Edge policy without centralizing business logic'},explanation:{pt:'Gateway centraliza TLS, autenticação grossa, routing, quota e observabilidade. WAF filtra ataques HTTP. Autorização fina continua no serviço.',en:'A gateway centralizes TLS, coarse authentication, routing, quotas, and observability. A WAF filters HTTP attacks. Fine-grained authorization stays in the service.'},steps:[{pt:'Tráfego HTTPS chega ao edge.',en:'HTTPS traffic reaches the edge.'},{pt:'WAF aplica filtros de camada HTTP.',en:'WAF applies HTTP-layer filters.'},{pt:'Gateway valida identidade/quota e roteia.',en:'Gateway validates identity/quota and routes.'},{pt:'Serviço aplica autorização e regra de negócio.',en:'Service applies authorization and business logic.'}]},
  {key:'validation',title:'Input validation',subtitle:{pt:'Todo payload é não confiável',en:'Treat every payload as untrusted'},explanation:{pt:'Valide schema, tamanho, ranges, formatos e content type. Use queries parametrizadas e autorização object/function-level para evitar injection e BOLA/BFLA.',en:'Validate schema, size, ranges, formats, and content type. Use parameterized queries and object/function-level authorization to prevent injection and BOLA/BFLA.'},steps:[{pt:'Parse com limite de tamanho.',en:'Parse with a size limit.'},{pt:'Valide schema e tipos.',en:'Validate schema and types.'},{pt:'Autorize o objeto/ação solicitados.',en:'Authorize the requested object/action.'},{pt:'Somente então execute a regra de negócio.',en:'Only then execute business logic.'}]},
  {key:'mtls',title:'mTLS service-to-service',subtitle:{pt:'Identidade forte para workloads',en:'Strong workload identity'},explanation:{pt:'mTLS autentica os dois lados. Use CA/workload identity, certificados curtos e rotação automática; combine com policy, não apenas “certificado válido”.',en:'mTLS authenticates both sides. Use a CA/workload identity, short-lived certificates, and automatic rotation; combine it with policy, not just “valid certificate”.'},steps:[{pt:'CA emite identidade para cada workload.',en:'CA issues identity to each workload.'},{pt:'Cliente e servidor apresentam certificados.',en:'Client and server present certificates.'},{pt:'Ambos validam cadeia e identidade.',en:'Both validate chain and identity.'},{pt:'Canal cifrado é liberado conforme policy.',en:'Encrypted channel is allowed according to policy.'}]},
];

const methods = [
  ['GET','Ler uma representação de um recurso.','Read a representation of a resource.','Sim / Yes','Sim / Yes','Normalmente cacheável; não deve alterar estado por intenção. / Normally cacheable; should not change state by intent.'],
  ['HEAD','Igual ao GET, mas sem corpo da resposta.','Same as GET, but without response content.','Sim / Yes','Sim / Yes','Útil para metadados, validators e existência. / Useful for metadata, validators, and existence checks.'],
  ['POST','Processar o payload conforme a semântica do recurso.','Process request content according to resource semantics.','Não / No','Não / No','Criação, comandos e operações não idempotentes são casos comuns. / Creation, commands, and non-idempotent operations are common.'],
  ['PUT','Criar/substituir completamente o estado do recurso alvo.','Create/replace the complete state of the target resource.','Não / No','Sim / Yes','Repetir o mesmo PUT deve convergir ao mesmo estado. / Repeating the same PUT should converge to the same state.'],
  ['PATCH','Aplicar modificações parciais.','Apply partial modifications.','Não / No','Depende / Depends','A idempotência depende do patch format/operação. RFC 5789 define PATCH. / Idempotency depends on the patch format/operation. RFC 5789 defines PATCH.'],
  ['DELETE','Remover o recurso alvo.','Remove the target resource.','Não / No','Sim / Yes','Repetir pode retornar outro status, mas o efeito desejado continua “ausente”. / Repeating may return a different status, but the intended effect remains “absent”.'],
  ['OPTIONS','Descrever opções de comunicação suportadas.','Describe supported communication options.','Sim / Yes','Sim / Yes','Usado também em CORS preflight. / Also used in CORS preflight.'],
  ['CONNECT','Estabelecer um túnel para o destino.','Establish a tunnel to the target.','Não / No','Não / No','Comum em proxies, por exemplo túnel HTTPS. / Common in proxies, e.g. HTTPS tunneling.'],
  ['TRACE','Loop-back de diagnóstico da requisição.','Diagnostic loop-back of the request.','Sim / Yes','Sim / Yes','Frequentemente desabilitado em produção por segurança. / Frequently disabled in production for security.'],
];

function Card<K extends string>({ card, diagram, open, toggle }: { card: GuideCard<K>; diagram: ReactNode; open: boolean; toggle: () => void }) {
  const { locale } = useLanguage();
  const pick = (v: Bilingual) => locale === 'en' ? v.en : v.pt;
  return <article className={`api-guide-card ${open ? 'is-expanded' : ''}`}>
    <button type="button" className="api-guide-trigger" onClick={toggle} aria-expanded={open}>
      <span><strong>{card.title}</strong><small>{pick(card.subtitle)}</small></span><span aria-hidden="true">{open ? '−' : '+'}</span>
    </button>
    {open ? <div className="api-guide-content">
      <p>{pick(card.explanation)}</p>
      <ol>{card.steps.map((step,index)=><li key={index}><span>{index+1}</span><p>{pick(step)}</p></li>)}</ol>
      {card.bestFor ? <p className="reference-note"><strong>{locale==='en'?'Best for:':'Melhor para:'}</strong> {pick(card.bestFor)}</p> : null}
      {card.warning ? <p className="reference-note"><strong>{locale==='en'?'Watch out:':'Atenção:'}</strong> {pick(card.warning)}</p> : null}
      {diagram}
    </div> : null}
  </article>;
}

function CardGroup<K extends string>({ cards, diagramFor }: { cards: GuideCard<K>[]; diagramFor: (key: K) => ReactNode }) {
  const [open, setOpen] = useState<K | null>(null);
  return <div className="api-guide-grid">{cards.map(card=><Card key={card.key} card={card} diagram={diagramFor(card.key)} open={open===card.key} toggle={()=>setOpen(open===card.key?null:card.key)} />)}</div>;
}

export function ApiReference() {
  const { locale, t } = useLanguage();
  return <>
    <section className="article-section" id="api-architectures">
      <h2>{t('Arquiteturas, protocolos e padrões de API', 'API architectures, protocols, and patterns')}</h2>
      <p className="section-summary">{t('Os itens abaixo não são equivalentes diretos: REST/GraphQL/gRPC/SOAP modelam APIs; WebSocket cria um canal bidirecional; Webhook é callback HTTP; MQTT e AMQP são protocolos de messaging.', 'The items below are not direct equivalents: REST/GraphQL/gRPC/SOAP model APIs; WebSocket creates a bidirectional channel; Webhook is an HTTP callback; MQTT and AMQP are messaging protocols.')}</p>
      <CardGroup cards={architectures} diagramFor={(key)=><TopicDiagram spec={getApiArchitectureDiagram(key)} />} />
    </section>

    <section className="article-section" id="api-performance">
      <h2>{t('Performance e escalabilidade de APIs', 'API performance and scalability')}</h2>
      <p className="section-summary">{t('Otimização saudável reduz trabalho por request, bytes transferidos, criação de conexões e tempo no critical path antes de simplesmente adicionar CPU.', 'Healthy optimization reduces work per request, transferred bytes, connection creation, and critical-path time before simply adding CPU.')}</p>
      <CardGroup cards={performance} diagramFor={(key)=><TopicDiagram spec={getApiPerformanceDiagram(key)} />} />
    </section>

    <section className="article-section" id="api-security">
      <h2>{t('Segurança de APIs — defesa em profundidade', 'API security — defense in depth')}</h2>
      <p className="section-summary">{t('TLS, identidade, autorização, validação, rate limiting, logging e segmentação devem funcionar juntos. Nenhum controle isolado torna uma API segura.', 'TLS, identity, authorization, validation, rate limiting, logging, and segmentation must work together. No single control makes an API secure.')}</p>
      <CardGroup cards={security} diagramFor={(key)=><TopicDiagram spec={getApiSecurityDiagram(key)} />} />
      <div className="reference-note"><strong>{t('Best practices:', 'Best practices:')}</strong> {t('HTTPS obrigatório; tokens curtos; least privilege; object-level authorization em toda operação; schema e size limits; rate limiting por identidade; secrets fora do código; logs sem credenciais/tokens; versionamento e deprecation explícitos; CORS restritivo; timeouts/deadlines; idempotency keys em operações críticas; auditoria e monitoração de abuso.', 'Require HTTPS; short-lived tokens; least privilege; object-level authorization on every operation; schema and size limits; identity-aware rate limiting; secrets outside code; logs without credentials/tokens; explicit versioning and deprecation; restrictive CORS; timeouts/deadlines; idempotency keys for critical operations; auditability and abuse monitoring.')}</div>
    </section>

    <section className="article-section" id="http-methods">
      <h2>{t('Métodos HTTP', 'HTTP methods')}</h2>
      <p className="section-summary">{t('Safe significa que a intenção do método é somente leitura. Idempotent significa que repetir a mesma requisição tem o mesmo efeito desejado no servidor, embora status, timestamps ou logs possam mudar.', 'Safe means the method is intended to be read-only. Idempotent means repeating the same request has the same intended server-side effect, even though status codes, timestamps, or logs may differ.')}</p>
      <div className="table-wrap"><table className="reference-table"><thead><tr><th>Method</th><th>{t('Semântica', 'Semantics')}</th><th>Safe</th><th>Idempotent</th><th>{t('Notas', 'Notes')}</th></tr></thead><tbody>{methods.map(([method,pt,en,safe,idempotent,notes])=><tr key={method}><td><code>{method}</code></td><td>{locale==='en'?en:pt}</td><td>{safe}</td><td>{idempotent}</td><td>{notes.split(' / ')[locale==='en'?1:0] ?? notes}</td></tr>)}</tbody></table></div>
      <p className="technical-source-note">RFC 9110 define GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS e TRACE; RFC 5789 define PATCH.</p>
    </section>
  </>;
}
