image:
  repository: josecarlosjr/it-wiki
  tag: sha-ec07648f192c
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: internal-ca
  hosts:
    - host: it-wiki.home.arpa
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: it-wiki-tls
      hosts:
        - it-wiki.home.arpa
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
