image:
  repository: josecarlosjr/it-wiki
  tag: sha-9cddd1d8aac0
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: it-wiki.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: it-wiki-tls
      hosts:
        - it-wiki.example.com
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
